Script started on 2020-02-12 12:38:11+01:00 [TERM="xterm-256color" TTY="/dev/pts/29" COLUMNS="240" LINES="28"]
[0;32m[0m[1;34mbrauner[1;37m@[1;33mwittgenstein[1;37m|[1;33m~/src/git/cground/shiftfs_fsid_perf[1;32m[1;37m|[1;36mgithub-master %=
[0m[1;34m>[0m[0;32m[0m asciinema play demo2.play 
[?1h=[H[2J[?12l[?25h[?1000l[?1002l[?1006l[?1005l[c(B[m[?12;25h[?12l[?25h[?1003l[?1006l[?2004l[1;1H[1;28r]112[2;15H[?1006h[?1002h[?25l[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[2;15H[?12l[?25h(B[m[?12;25h[?12l[?25h[?1003l[?1006l[?2004l[1;1H[1;28r[2;15H[?1006h[?1002h[?25l[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[2;15H[?12l[?25h# Setting up a container runtime without fsid mappings.
[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[32m[1m[2;1Hroot@e1-vm(B[m:[34m[1m~(B[m# # Setting up a container runtime without fsid mappings.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[3;15H[?12l[?25h
[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[32m[1m[2;1Hroot@e1-vm(B[m:[34m[1m~(B[m# # Setting up a container runtime without fsid mappings.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[4;15H[?12l[?25h# The currene[Kt status quo is that fsid mappings are always identical to id mappings.
[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[32m[1m[2;1Hroot@e1-vm(B[m:[34m[1m~(B[m# # Setting up a container runtime without fsid mappings.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # The current status quo is that fsid mappings are always identical to id mappings.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[5;15H[?12l[?25h# This behavior is till[K[K[K[Kstill the same even after the introduction of fsid mappings.
[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[32m[1m[2;1Hroot@e1-vm(B[m:[34m[1m~(B[m# # Setting up a container runtime without fsid mappings.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # The current status quo is that fsid mappings are always identical to id mappings.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # This behavior is still the same even after the introduction of fsid mappings.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[6;15H[?12l[?25h# Let's show this:
[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[32m[1m[2;1Hroot@e1-vm(B[m:[34m[1m~(B[m# # Setting up a container runtime without fsid mappings.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # The current status quo is that fsid mappings are always identical to id mappings.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # This behavior is still the same even after the introduction of fsid mappings.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # Let's show this:[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[7;15H[?12l[?25hlxc launch images:fedora/31 fed1[?25l[32m[1m[2;1Hroot@e1-vm(B[m:[34m[1m~(B[m# # Setting up a container runtime without fsid mappings.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # The current status quo is that fsid mappings are always identical to id mappings.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # This behavior is still the same even after the introduction of fsid mappings.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # Let's show this:[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc launch images:fedora/31 fed1[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[7;47H[?12l[?25h
Creating fed1
Starting fed1
[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[32m[1m[2;1Hroot@e1-vm(B[m:[34m[1m~(B[m# # Setting up a container runtime without fsid mappings.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # The current status quo is that fsid mappings are always identical to id mappings.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # This behavior is still the same even after the introduction of fsid mappings.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # Let's show this:[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc launch images:fedora/31 fed1[K
Creating fed1[K
Starting fed1[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[10;15H[?12l[?25hlxc exec fed1 bash
[?25l[38;5;230m[48;5;239m[H[$5|demo]                                         0:0- 1:1*                                         [%18|0|root@fed1:~] (B[m[11;1H[?12l[?25h[root@fed1 ~]# cat /proc/self/uid_map 
         0     100000  100000000
[root@fed1 ~]# cat /proc/self/gid_map 
         0     100000  100000000
[root@fed1 ~]# [?25l[32m[1m[2;1Hroot@e1-vm(B[m:[34m[1m~(B[m# # Setting up a container runtime without fsid mappings.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # The current status quo is that fsid mappings are always identical to id mappings.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # This behavior is still the same even after the introduction of fsid mappings.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # Let's show this:[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc launch images:fedora/31 fed1[K
Creating fed1[K
Starting fed1[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec fed1 bash[K
[root@fed1 ~]# cat /proc/self/uid_map [K
         0     100000  100000000[K
[root@fed1 ~]# cat /proc/self/gid_map [K
         0     100000  100000000[K
[root@fed1 ~]# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                         0:0- 1:1*                                         [%18|0|root@fed1:~] (B[m[15;16H[?12l[?25hcat /proc/self/fsuid_map 
[root@fed1 ~]# [?25l[32m[1m[2;1Hroot@e1-vm(B[m:[34m[1m~(B[m# # Setting up a container runtime without fsid mappings.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # The current status quo is that fsid mappings are always identical to id mappings.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # This behavior is still the same even after the introduction of fsid mappings.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # Let's show this:[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc launch images:fedora/31 fed1[K
Creating fed1[K
Starting fed1[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec fed1 bash[K
[root@fed1 ~]# cat /proc/self/uid_map [K
         0     100000  100000000[K
[root@fed1 ~]# cat /proc/self/gid_map [K
         0     100000  100000000[K
[root@fed1 ~]# cat /proc/self/fsuid_map [K
[root@fed1 ~]# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                         0:0- 1:1*                                         [%18|0|root@fed1:~] (B[m[16;16H[?12l[?25hcat /proc/self/fsgid_map 
[root@fed1 ~]# [?25l[32m[1m[2;1Hroot@e1-vm(B[m:[34m[1m~(B[m# # Setting up a container runtime without fsid mappings.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # The current status quo is that fsid mappings are always identical to id mappings.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # This behavior is still the same even after the introduction of fsid mappings.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # Let's show this:[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc launch images:fedora/31 fed1[K
Creating fed1[K
Starting fed1[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec fed1 bash[K
[root@fed1 ~]# cat /proc/self/uid_map [K
         0     100000  100000000[K
[root@fed1 ~]# cat /proc/self/gid_map [K
         0     100000  100000000[K
[root@fed1 ~]# cat /proc/self/fsuid_map [K
[root@fed1 ~]# cat /proc/self/fsgid_map [K
[root@fed1 ~]# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                         0:0- 1:1*                                         [%18|0|root@fed1:~] (B[m[17;16H[?12l[?25h# The rootfs is mapped to the id mapping specified and behaves just like it would have
[root@fed1 ~]# [?25l[32m[1m[2;1Hroot@e1-vm(B[m:[34m[1m~(B[m# # Setting up a container runtime without fsid mappings.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # The current status quo is that fsid mappings are always identical to id mappings.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # This behavior is still the same even after the introduction of fsid mappings.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # Let's show this:[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc launch images:fedora/31 fed1[K
Creating fed1[K
Starting fed1[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec fed1 bash[K
[root@fed1 ~]# cat /proc/self/uid_map [K
         0     100000  100000000[K
[root@fed1 ~]# cat /proc/self/gid_map [K
         0     100000  100000000[K
[root@fed1 ~]# cat /proc/self/fsuid_map [K
[root@fed1 ~]# cat /proc/self/fsgid_map [K
[root@fed1 ~]# # The rootfs is mapped to the id mapping specified and behaves just like it would have[K
[root@fed1 ~]# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                         0:0- 1:1*                                         [%18|0|root@fed1:~] (B[m[18;16H[?12l[?25h# beo[Kfore the introduction of fsid mappings.
[root@fed1 ~]# [?25l[32m[1m[2;1Hroot@e1-vm(B[m:[34m[1m~(B[m# # Setting up a container runtime without fsid mappings.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # The current status quo is that fsid mappings are always identical to id mappings.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # This behavior is still the same even after the introduction of fsid mappings.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # Let's show this:[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc launch images:fedora/31 fed1[K
Creating fed1[K
Starting fed1[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec fed1 bash[K
[root@fed1 ~]# cat /proc/self/uid_map [K
         0     100000  100000000[K
[root@fed1 ~]# cat /proc/self/gid_map [K
         0     100000  100000000[K
[root@fed1 ~]# cat /proc/self/fsuid_map [K
[root@fed1 ~]# cat /proc/self/fsgid_map [K
[root@fed1 ~]# # The rootfs is mapped to the id mapping specified and behaves just like it would have[K
[root@fed1 ~]# # before the introduction of fsid mappings.[K
[root@fed1 ~]# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                         0:0- 1:1*                                         [%18|0|root@fed1:~] (B[m[19;16H[?12l[?25hls -al 
total 12
dr-xr-x--- 1 root root  64 Feb 10 20:34 [38;5;33m.
[39mdr-xr-xr-x 1 root root 176 Feb 11 00:16 [38;5;33m..
[39m-rw-r--r-- 1 root root  18 Feb 10 20:34 .bash_logout
-rw-r--r-- 1 root root 141 Feb 10 20:34 .bash_profile
-rw-r--r-- 1 root root 376 Feb 10 20:34 .bashrc
[root@fed1 ~]# [?25l[32m[1m[2;1Hroot@e1-vm(B[m:[34m[1m~(B[m# # Setting up a container runtime without fsid mappings.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # The current status quo is that fsid mappings are always identical to id mappings.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # This behavior is still the same even after the introduction of fsid mappings.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # Let's show this:[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc launch images:fedora/31 fed1[K
Creating fed1[K
Starting fed1[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec fed1 bash[K
[root@fed1 ~]# cat /proc/self/uid_map [K
         0     100000  100000000[K
[root@fed1 ~]# cat /proc/self/gid_map [K
         0     100000  100000000[K
[root@fed1 ~]# cat /proc/self/fsuid_map [K
[root@fed1 ~]# cat /proc/self/fsgid_map [K
[root@fed1 ~]# # The rootfs is mapped to the id mapping specified and behaves just like it would have[K
[root@fed1 ~]# # before the introduction of fsid mappings.[K
[root@fed1 ~]# ls -al [K
total 12[K
dr-xr-x--- 1 root root  64 Feb 10 20:34 [38;5;33m.[39m[K
dr-xr-xr-x 1 root root 176 Feb 11 00:16 [38;5;33m..[39m[K
-rw-r--r-- 1 root root  18 Feb 10 20:34 .bash_logout[K
-rw-r--r-- 1 root root 141 Feb 10 20:34 .bash_profile[K
-rw-r--r-- 1 root root 376 Feb 10 20:34 .bashrc[K
[root@fed1 ~]# [K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                         0:0- 1:1*                                         [%18|0|root@fed1:~] (B[m[26;16H[?12l[?25hls -al /
[2;28r[4S[23dtotal 16
dr-xr-xr-x   1 root   root    176 Feb 11 00:16 [38;5;33m.
[39mdr-xr-xr-x   1 root   root    176 Feb 11 00:16 [38;5;33m..
[39m-rw-r--r--   1 root   root      0 Feb 11 00:16 .autorelabel
lrwxrwxrwx   1 root   root      7 Jul 25  2019 [38;5;51mbin[39m -> [38;5;33musr/bin[1;28r[28;1H(B[m[2;28r[19S[9ddr-xr-xr-x   1 root   root      0 Jul 25  2019 [38;5;33mboot
[39mdrwxr-xr-x   8 root   root    480 Feb 11 00:16 [38;5;33mdev
[39mdrwxr-xr-x   1 root   root   2086 Feb 11 00:16 [38;5;33metc
[39mdrwxr-xr-x   1 root   root      0 Jul 25  2019 [38;5;33mhome
[39mlrwxrwxrwx   1 root   root      7 Jul 25  2019 [38;5;51mlib[39m -> [38;5;33musr/lib
[39mlrwxrwxrwx   1 root   root      9 Jul 25  2019 [38;5;51mlib64[39m -> [38;5;33musr/lib64
[39mdrwx------   1 root   root      0 Feb 10 05:47 [38;5;33mlost+found
[39mdrwxr-xr-x   1 root   root      0 Jul 25  2019 [38;5;33mmedia
[39mdrwxr-xr-x   1 root   root      0 Jul 25  2019 [38;5;33mmnt
[39mdrwxr-xr-x   1 root   root      0 Jul 25  2019 [38;5;33mopt
[39mdr-xr-xr-x 242 nobody nobody    0 Feb 11 00:16 [38;5;33mproc
[39mdr-xr-x---   1 root   root     64 Feb 10 20:34 [38;5;33mroot
[39mdrwxr-xr-x  16 root   root    380 Feb 11 00:16 [38;5;33mrun
[39mlrwxrwxrwx   1 root   root      8 Jul 25  2019 [38;5;51msbin[39m -> [38;5;33musr/sbin
[39mdrwxr-xr-x   1 root   root      0 Jul 25  2019 [38;5;33msrv
[39mdr-xr-xr-x  13 nobody nobody    0 Feb 11 00:16 [38;5;33msys
[39mdrwxrwxrwt   9 root   root    180 Feb 11 00:17 [38;5;16m[102mtmp
[39m[49mdrwxr-xr-x   1 root   root    100 Feb 10 05:47 [38;5;33musr
[39mdrwxr-xr-x   1 root   root    170 Feb 11 00:16 [38;5;33mvar
[39m[root@fed1 ~]# [1;28r[28;16H[?25l[2;1H-rw-r--r-- 1 root root 376 Feb 10 20:34 .bashrc[K
[root@fed1 ~]# ls -al /[K
total 16[K
dr-xr-xr-x   1 root   root    176 Feb 11 00:16 [38;5;33m.[39m[K
dr-xr-xr-x   1 root   root    176 Feb 11 00:16 [38;5;33m..[39m[K
-rw-r--r--   1 root   root      0 Feb 11 00:16 .autorelabel[K
lrwxrwxrwx   1 root   root      7 Jul 25  2019 [38;5;51mbin[39m -> [38;5;33musr/bin[39m[K
dr-xr-xr-x   1 root   root      0 Jul 25  2019 [38;5;33mboot[39m[K
drwxr-xr-x   8 root   root    480 Feb 11 00:16 [38;5;33mdev[39m[K
drwxr-xr-x   1 root   root   2086 Feb 11 00:16 [38;5;33metc[39m[K
drwxr-xr-x   1 root   root      0 Jul 25  2019 [38;5;33mhome[39m[K
lrwxrwxrwx   1 root   root      7 Jul 25  2019 [38;5;51mlib[39m -> [38;5;33musr/lib[39m[K
lrwxrwxrwx   1 root   root      9 Jul 25  2019 [38;5;51mlib64[39m -> [38;5;33musr/lib64[39m[K
drwx------   1 root   root      0 Feb 10 05:47 [38;5;33mlost+found[39m[K
drwxr-xr-x   1 root   root      0 Jul 25  2019 [38;5;33mmedia[39m[K
drwxr-xr-x   1 root   root      0 Jul 25  2019 [38;5;33mmnt[39m[K
drwxr-xr-x   1 root   root      0 Jul 25  2019 [38;5;33mopt[39m[K
dr-xr-xr-x 242 nobody nobody    0 Feb 11 00:16 [38;5;33mproc[39m[K
dr-xr-x---   1 root   root     64 Feb 10 20:34 [38;5;33mroot[39m[K
drwxr-xr-x  16 root   root    380 Feb 11 00:16 [38;5;33mrun[39m[K
lrwxrwxrwx   1 root   root      8 Jul 25  2019 [38;5;51msbin[39m -> [38;5;33musr/sbin[39m[K
drwxr-xr-x   1 root   root      0 Jul 25  2019 [38;5;33msrv[39m[K
dr-xr-xr-x  13 nobody nobody    0 Feb 11 00:16 [38;5;33msys[39m[K
drwxrwxrwt   9 root   root    180 Feb 11 00:17 [38;5;16m[102mtmp[39m[49m[K
drwxr-xr-x   1 root   root    100 Feb 10 05:47 [38;5;33musr[39m[K
drwxr-xr-x   1 root   root    170 Feb 11 00:16 [38;5;33mvar[39m[K
[root@fed1 ~]# [K[38;5;230m[48;5;239m[H[$5|demo]                                         0:0- 1:1*                                         [%18|0|root@fed1:~] (B[m[28;16H[?12l[?25htouch /AAAA[2;28r[28;1H
[1;28r[28;1H[root@fed1 ~]# [?25l[2;1H[root@fed1 ~]# ls -al /[K
total 16[K
dr-xr-xr-x   1 root   root    176 Feb 11 00:16 [38;5;33m.[39m[K
dr-xr-xr-x   1 root   root    176 Feb 11 00:16 [38;5;33m..[39m[K
-rw-r--r--   1 root   root      0 Feb 11 00:16 .autorelabel[K
lrwxrwxrwx   1 root   root      7 Jul 25  2019 [38;5;51mbin[39m -> [38;5;33musr/bin[39m[K
dr-xr-xr-x   1 root   root      0 Jul 25  2019 [38;5;33mboot[39m[K
drwxr-xr-x   8 root   root    480 Feb 11 00:16 [38;5;33mdev[39m[K
drwxr-xr-x   1 root   root   2086 Feb 11 00:16 [38;5;33metc[39m[K
drwxr-xr-x   1 root   root      0 Jul 25  2019 [38;5;33mhome[39m[K
lrwxrwxrwx   1 root   root      7 Jul 25  2019 [38;5;51mlib[39m -> [38;5;33musr/lib[39m[K
lrwxrwxrwx   1 root   root      9 Jul 25  2019 [38;5;51mlib64[39m -> [38;5;33musr/lib64[39m[K
drwx------   1 root   root      0 Feb 10 05:47 [38;5;33mlost+found[39m[K
drwxr-xr-x   1 root   root      0 Jul 25  2019 [38;5;33mmedia[39m[K
drwxr-xr-x   1 root   root      0 Jul 25  2019 [38;5;33mmnt[39m[K
drwxr-xr-x   1 root   root      0 Jul 25  2019 [38;5;33mopt[39m[K
dr-xr-xr-x 242 nobody nobody    0 Feb 11 00:16 [38;5;33mproc[39m[K
dr-xr-x---   1 root   root     64 Feb 10 20:34 [38;5;33mroot[39m[K
drwxr-xr-x  16 root   root    380 Feb 11 00:16 [38;5;33mrun[39m[K
lrwxrwxrwx   1 root   root      8 Jul 25  2019 [38;5;51msbin[39m -> [38;5;33musr/sbin[39m[K
drwxr-xr-x   1 root   root      0 Jul 25  2019 [38;5;33msrv[39m[K
dr-xr-xr-x  13 nobody nobody    0 Feb 11 00:16 [38;5;33msys[39m[K
drwxrwxrwt   9 root   root    180 Feb 11 00:17 [38;5;16m[102mtmp[39m[49m[K
drwxr-xr-x   1 root   root    100 Feb 10 05:47 [38;5;33musr[39m[K
drwxr-xr-x   1 root   root    170 Feb 11 00:16 [38;5;33mvar[39m[K
[root@fed1 ~]# touch /AAAA[K
[root@fed1 ~]# [K[38;5;230m[48;5;239m[H[$5|demo]                                         0:0- 1:1*                                         [%18|0|root@fed1:~] (B[m[28;16H[?12l[?25hmkdir /BBBB[2;28r[28;1H
[1;28r[28;1H[root@fed1 ~]# [?25l[2;1Htotal 16[K
dr-xr-xr-x   1 root   root    176 Feb 11 00:16 [38;5;33m.[39m[K
dr-xr-xr-x   1 root   root    176 Feb 11 00:16 [38;5;33m..[39m[K
-rw-r--r--   1 root   root      0 Feb 11 00:16 .autorelabel[K
lrwxrwxrwx   1 root   root      7 Jul 25  2019 [38;5;51mbin[39m -> [38;5;33musr/bin[39m[K
dr-xr-xr-x   1 root   root      0 Jul 25  2019 [38;5;33mboot[39m[K
drwxr-xr-x   8 root   root    480 Feb 11 00:16 [38;5;33mdev[39m[K
drwxr-xr-x   1 root   root   2086 Feb 11 00:16 [38;5;33metc[39m[K
drwxr-xr-x   1 root   root      0 Jul 25  2019 [38;5;33mhome[39m[K
lrwxrwxrwx   1 root   root      7 Jul 25  2019 [38;5;51mlib[39m -> [38;5;33musr/lib[39m[K
lrwxrwxrwx   1 root   root      9 Jul 25  2019 [38;5;51mlib64[39m -> [38;5;33musr/lib64[39m[K
drwx------   1 root   root      0 Feb 10 05:47 [38;5;33mlost+found[39m[K
drwxr-xr-x   1 root   root      0 Jul 25  2019 [38;5;33mmedia[39m[K
drwxr-xr-x   1 root   root      0 Jul 25  2019 [38;5;33mmnt[39m[K
drwxr-xr-x   1 root   root      0 Jul 25  2019 [38;5;33mopt[39m[K
dr-xr-xr-x 242 nobody nobody    0 Feb 11 00:16 [38;5;33mproc[39m[K
dr-xr-x---   1 root   root     64 Feb 10 20:34 [38;5;33mroot[39m[K
drwxr-xr-x  16 root   root    380 Feb 11 00:16 [38;5;33mrun[39m[K
lrwxrwxrwx   1 root   root      8 Jul 25  2019 [38;5;51msbin[39m -> [38;5;33musr/sbin[39m[K
drwxr-xr-x   1 root   root      0 Jul 25  2019 [38;5;33msrv[39m[K
dr-xr-xr-x  13 nobody nobody    0 Feb 11 00:16 [38;5;33msys[39m[K
drwxrwxrwt   9 root   root    180 Feb 11 00:17 [38;5;16m[102mtmp[39m[49m[K
drwxr-xr-x   1 root   root    100 Feb 10 05:47 [38;5;33musr[39m[K
drwxr-xr-x   1 root   root    170 Feb 11 00:16 [38;5;33mvar[39m[K
[root@fed1 ~]# touch /AAAA[K
[root@fed1 ~]# mkdir /BBBB[K
[root@fed1 ~]# [K[38;5;230m[48;5;239m[H[$5|demo]                                         0:0- 1:1*                                         [%18|0|root@fed1:~] (B[m[28;16H[?12l[?25hls -al /[2;28r[28;1H
[1;28r[28;1H[2;28r[28;1H
[Atotal 16[1;28r[28;1H[2;28r[2S[26ddr-xr-xr-x   1 root   root    192 Feb 11 00:17 [38;5;33m.
[39mdr-xr-xr-x   1 root   root    192 Feb 11 00:17 [38;5;33m..[1;28r[28;1H(B[m[2;28r[17S[11d-rw-r--r--   1 root   root      0 Feb 11 00:16 .autorelabel
-rw-r--r--   1 root   root      0 Feb 11 00:17 AAAA
drwxr-xr-x   1 root   root      0 Feb 11 00:17 [38;5;33mBBBB
[39mlrwxrwxrwx   1 root   root      7 Jul 25  2019 [38;5;51mbin[39m -> [38;5;33musr/bin
[39mdr-xr-xr-x   1 root   root      0 Jul 25  2019 [38;5;33mboot
[39mdrwxr-xr-x   8 root   root    480 Feb 11 00:16 [38;5;33mdev
[39mdrwxr-xr-x   1 root   root   2086 Feb 11 00:16 [38;5;33metc
[39mdrwxr-xr-x   1 root   root      0 Jul 25  2019 [38;5;33mhome
[39mlrwxrwxrwx   1 root   root      7 Jul 25  2019 [38;5;51mlib[39m -> [38;5;33musr/lib
[39mlrwxrwxrwx   1 root   root      9 Jul 25  2019 [38;5;51mlib64[39m -> [38;5;33musr/lib64
[39mdrwx------   1 root   root      0 Feb 10 05:47 [38;5;33mlost+found
[39mdrwxr-xr-x   1 root   root      0 Jul 25  2019 [38;5;33mmedia
[39mdrwxr-xr-x   1 root   root      0 Jul 25  2019 [38;5;33mmnt
[39mdrwxr-xr-x   1 root   root      0 Jul 25  2019 [38;5;33mopt
[39mdr-xr-xr-x 242 nobody nobody    0 Feb 11 00:16 [38;5;33mproc
[39mdr-xr-x---   1 root   root     64 Feb 10 20:34 [38;5;33mroot
[39mdrwxr-xr-x  16 root   root    380 Feb 11 00:16 [38;5;33mrun[1;28r[28;1H(B[m[2;28r[6S[22dlrwxrwxrwx   1 root   root      8 Jul 25  2019 [38;5;51msbin[39m -> [38;5;33musr/sbin
[39mdrwxr-xr-x   1 root   root      0 Jul 25  2019 [38;5;33msrv
[39mdr-xr-xr-x  13 nobody nobody    0 Feb 11 00:16 [38;5;33msys
[39mdrwxrwxrwt   9 root   root    180 Feb 11 00:17 [38;5;16m[102mtmp
[39m[49mdrwxr-xr-x   1 root   root    100 Feb 10 05:47 [38;5;33musr
[39mdrwxr-xr-x   1 root   root    170 Feb 11 00:16 [38;5;33mvar[1;28r[28;1H(B[m[root@fed1 ~]# [?25l[2;1Htotal 16[K
dr-xr-xr-x   1 root   root    192 Feb 11 00:17 [38;5;33m.[39m[K
dr-xr-xr-x   1 root   root    192 Feb 11 00:17 [38;5;33m..[39m[K
-rw-r--r--   1 root   root      0 Feb 11 00:16 .autorelabel[K
-rw-r--r--   1 root   root      0 Feb 11 00:17 AAAA[K
drwxr-xr-x   1 root   root      0 Feb 11 00:17 [38;5;33mBBBB[39m[K
lrwxrwxrwx   1 root   root      7 Jul 25  2019 [38;5;51mbin[39m -> [38;5;33musr/bin[39m[K
dr-xr-xr-x   1 root   root      0 Jul 25  2019 [38;5;33mboot[39m[K
drwxr-xr-x   8 root   root    480 Feb 11 00:16 [38;5;33mdev[39m[K
drwxr-xr-x   1 root   root   2086 Feb 11 00:16 [38;5;33metc[39m[K
drwxr-xr-x   1 root   root      0 Jul 25  2019 [38;5;33mhome[39m[K
lrwxrwxrwx   1 root   root      7 Jul 25  2019 [38;5;51mlib[39m -> [38;5;33musr/lib[39m[K
lrwxrwxrwx   1 root   root      9 Jul 25  2019 [38;5;51mlib64[39m -> [38;5;33musr/lib64[39m[K
drwx------   1 root   root      0 Feb 10 05:47 [38;5;33mlost+found[39m[K
drwxr-xr-x   1 root   root      0 Jul 25  2019 [38;5;33mmedia[39m[K
drwxr-xr-x   1 root   root      0 Jul 25  2019 [38;5;33mmnt[39m[K
drwxr-xr-x   1 root   root      0 Jul 25  2019 [38;5;33mopt[39m[K
dr-xr-xr-x 242 nobody nobody    0 Feb 11 00:16 [38;5;33mproc[39m[K
dr-xr-x---   1 root   root     64 Feb 10 20:34 [38;5;33mroot[39m[K
drwxr-xr-x  16 root   root    380 Feb 11 00:16 [38;5;33mrun[39m[K
lrwxrwxrwx   1 root   root      8 Jul 25  2019 [38;5;51msbin[39m -> [38;5;33musr/sbin[39m[K
drwxr-xr-x   1 root   root      0 Jul 25  2019 [38;5;33msrv[39m[K
dr-xr-xr-x  13 nobody nobody    0 Feb 11 00:16 [38;5;33msys[39m[K
drwxrwxrwt   9 root   root    180 Feb 11 00:17 [38;5;16m[102mtmp[39m[49m[K
drwxr-xr-x   1 root   root    100 Feb 10 05:47 [38;5;33musr[39m[K
drwxr-xr-x   1 root   root    170 Feb 11 00:16 [38;5;33mvar[39m[K
[root@fed1 ~]# [K[38;5;230m[48;5;239m[H[$5|demo]                                         0:0- 1:1*                                         [%18|0|root@fed1:~] (B[m[28;16H[?12l[?25h# [K[K[2;28r[28;1H
[27;16Hexit[1;28r[28;1H[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[2;1Hdr-xr-xr-x   1 root   root    192 Feb 11 00:17 [38;5;33m.[39m[K
dr-xr-xr-x   1 root   root    192 Feb 11 00:17 [38;5;33m..[39m[K
-rw-r--r--   1 root   root      0 Feb 11 00:16 .autorelabel[K
-rw-r--r--   1 root   root      0 Feb 11 00:17 AAAA[K
drwxr-xr-x   1 root   root      0 Feb 11 00:17 [38;5;33mBBBB[39m[K
lrwxrwxrwx   1 root   root      7 Jul 25  2019 [38;5;51mbin[39m -> [38;5;33musr/bin[39m[K
dr-xr-xr-x   1 root   root      0 Jul 25  2019 [38;5;33mboot[39m[K
drwxr-xr-x   8 root   root    480 Feb 11 00:16 [38;5;33mdev[39m[K
drwxr-xr-x   1 root   root   2086 Feb 11 00:16 [38;5;33metc[39m[K
drwxr-xr-x   1 root   root      0 Jul 25  2019 [38;5;33mhome[39m[K
lrwxrwxrwx   1 root   root      7 Jul 25  2019 [38;5;51mlib[39m -> [38;5;33musr/lib[39m[K
lrwxrwxrwx   1 root   root      9 Jul 25  2019 [38;5;51mlib64[39m -> [38;5;33musr/lib64[39m[K
drwx------   1 root   root      0 Feb 10 05:47 [38;5;33mlost+found[39m[K
drwxr-xr-x   1 root   root      0 Jul 25  2019 [38;5;33mmedia[39m[K
drwxr-xr-x   1 root   root      0 Jul 25  2019 [38;5;33mmnt[39m[K
drwxr-xr-x   1 root   root      0 Jul 25  2019 [38;5;33mopt[39m[K
dr-xr-xr-x 242 nobody nobody    0 Feb 11 00:16 [38;5;33mproc[39m[K
dr-xr-x---   1 root   root     64 Feb 10 20:34 [38;5;33mroot[39m[K
drwxr-xr-x  16 root   root    380 Feb 11 00:16 [38;5;33mrun[39m[K
lrwxrwxrwx   1 root   root      8 Jul 25  2019 [38;5;51msbin[39m -> [38;5;33musr/sbin[39m[K
drwxr-xr-x   1 root   root      0 Jul 25  2019 [38;5;33msrv[39m[K
dr-xr-xr-x  13 nobody nobody    0 Feb 11 00:16 [38;5;33msys[39m[K
drwxrwxrwt   9 root   root    180 Feb 11 00:17 [38;5;16m[102mtmp[39m[49m[K
drwxr-xr-x   1 root   root    100 Feb 10 05:47 [38;5;33musr[39m[K
drwxr-xr-x   1 root   root    170 Feb 11 00:16 [38;5;33mvar[39m[K
[root@fed1 ~]# exit[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[28;15H[?12l[?25hc[Kls -al /var/lib/lxd/storage-pools/default/containers/fed1/rootfs/[2;28r[28;1H
[1;28r[28;1H[2;28r[28;1H
[Atotal 16[1;28r[28;1H[2;28r[6S[22ddr-xr-xr-x 1 100000 100000  192 Feb 11 00:17 [34m[1m.
(B[md--x------ 1 100000 root     78 Feb 11 00:16 [34m[1m..
(B[m-rw-r--r-- 1 100000 100000    0 Feb 11 00:16 .autorelabel
-rw-r--r-- 1 100000 100000    0 Feb 11 00:17 AAAA
drwxr-xr-x 1 100000 100000    0 Feb 11 00:17 [34m[1mBBBB
(B[mlrwxrwxrwx 1 100000 100000    7 Jul 25  2019 [36m[1mbin(B[m -> [34m[1musr/bin
(B[mdr-xr-xr-x 1 100000 100000    0 Jul 25  2019 [34m[1mboot[1;28r[28;50H(B[m[2;28r[2S[27ddrwxr-xr-x 1 100000 100000    0 Feb 10 20:39 [34m[1mdev[1;28r[28;1H(B[mdrwxr-xr-x 1 100000 100000 2086 Feb 11 00:16 [34m[1metc(B[m[2;28r[28;1H
[1;28r[28;1Hdrwxr-xr-x 1 100000 100000    0 Jul 25  2019 [34m[1mhome(B[m[2;28r[28;1H
[1;28r[28;1Hlrwxrwxrwx 1 100000 100000    7 Jul 25  2019 [36m[1mlib(B[m -> [34m[1musr/lib(B[m[2;28r[28;1H
[1;28r[28;1Hlrwxrwxrwx 1 100000 100000    9 Jul 25  2019 [36m[1mlib64(B[m -> [34m[1musr/lib64(B[m[2;28r[28;1H
[1;28r[28;1Hdrwx------ 1 100000 100000    0 Feb 10 05:47 [34m[1mlost+found(B[m[2;28r[28;1H
[1;28r[28;1Hdrwxr-xr-x 1 100000 100000    0 Jul 25  2019 [34m[1mmedia(B[m[2;28r[28;1H
[1;28r[28;1Hdrwxr-xr-x 1 100000 100000    0 Jul 25  2019 [34m[1mmnt(B[m[2;28r[28;1H
[1;28r[28;1Hdrwxr-xr-x 1 100000 100000    0 Jul 25  2019 [34m[1mopt(B[m[2;28r[28;1H
[1;28r[28;1Hdrwxr-xr-x 1 100000 100000    0 Feb 10 05:47 [34m[1mproc(B[m[2;28r[28;1H
[1;28r[28;1H[2;28r[3S[25ddr-xr-x--- 1 100000 100000   90 Feb 11 00:17 [34m[1mroot
(B[mdrwxr-xr-x 1 100000 100000  152 Feb 10 05:48 [34m[1mrun
(B[mlrwxrwxrwx 1 100000 100000    8 Jul 25  2019 [36m[1msbin(B[m -> [34m[1musr/sbin[1;28r[28;1H(B[m[2;28r[3S[25ddrwxr-xr-x 1 100000 100000    0 Jul 25  2019 [34m[1msrv
(B[mdrwxr-xr-x 1 100000 100000    0 Feb 10 05:47 [34m[1msys
(B[mdrwxrwxrwt 1 100000 100000    0 Feb 10 20:33 [30m[42mtmp[1;28r[28;1H(B[m[2;28r[28;1H
[Adrwxr-xr-x 1 100000 100000  100 Feb 10 05:47 [34m[1musr[1;28r[28;1H(B[m[2;28r[28;1H
[Adrwxr-xr-x 1 100000 100000  170 Feb 11 00:16 [34m[1mvar[1;28r[28;1H(B[m[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[2;1Htotal 16[K
dr-xr-xr-x 1 100000 100000  192 Feb 11 00:17 [34m[1m.(B[m[K
d--x------ 1 100000 root     78 Feb 11 00:16 [34m[1m..(B[m[K
-rw-r--r-- 1 100000 100000    0 Feb 11 00:16 .autorelabel[K
-rw-r--r-- 1 100000 100000    0 Feb 11 00:17 AAAA[K
drwxr-xr-x 1 100000 100000    0 Feb 11 00:17 [34m[1mBBBB(B[m[K
lrwxrwxrwx 1 100000 100000    7 Jul 25  2019 [36m[1mbin(B[m -> [34m[1musr/bin(B[m[K
dr-xr-xr-x 1 100000 100000    0 Jul 25  2019 [34m[1mboot(B[m[K
drwxr-xr-x 1 100000 100000    0 Feb 10 20:39 [34m[1mdev(B[m[K
drwxr-xr-x 1 100000 100000 2086 Feb 11 00:16 [34m[1metc(B[m[K
drwxr-xr-x 1 100000 100000    0 Jul 25  2019 [34m[1mhome(B[m[K
lrwxrwxrwx 1 100000 100000    7 Jul 25  2019 [36m[1mlib(B[m -> [34m[1musr/lib(B[m[K
lrwxrwxrwx 1 100000 100000    9 Jul 25  2019 [36m[1mlib64(B[m -> [34m[1musr/lib64(B[m[K
drwx------ 1 100000 100000    0 Feb 10 05:47 [34m[1mlost+found(B[m[K
drwxr-xr-x 1 100000 100000    0 Jul 25  2019 [34m[1mmedia(B[m[K
drwxr-xr-x 1 100000 100000    0 Jul 25  2019 [34m[1mmnt(B[m[K
drwxr-xr-x 1 100000 100000    0 Jul 25  2019 [34m[1mopt(B[m[K
drwxr-xr-x 1 100000 100000    0 Feb 10 05:47 [34m[1mproc(B[m[K
dr-xr-x--- 1 100000 100000   90 Feb 11 00:17 [34m[1mroot(B[m[K
drwxr-xr-x 1 100000 100000  152 Feb 10 05:48 [34m[1mrun(B[m[K
lrwxrwxrwx 1 100000 100000    8 Jul 25  2019 [36m[1msbin(B[m -> [34m[1musr/sbin(B[m[K
drwxr-xr-x 1 100000 100000    0 Jul 25  2019 [34m[1msrv(B[m[K
drwxr-xr-x 1 100000 100000    0 Feb 10 05:47 [34m[1msys(B[m[K
drwxrwxrwt 1 100000 100000    0 Feb 10 20:33 [30m[42mtmp[39m[49m[K
drwxr-xr-x 1 100000 100000  100 Feb 10 05:47 [34m[1musr(B[m[K
drwxr-xr-x 1 100000 100000  170 Feb 11 00:16 [34m[1mvar(B[m[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[28;15H[?12l[?25h# So container runtimes don't need to care about fsid mappings if they don't want[2;28r[28;1H
[1;28r[28;1H[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[2;1Hdr-xr-xr-x 1 100000 100000  192 Feb 11 00:17 [34m[1m.(B[m[K
d--x------ 1 100000 root     78 Feb 11 00:16 [34m[1m..(B[m[K
-rw-r--r-- 1 100000 100000    0 Feb 11 00:16 .autorelabel[K
-rw-r--r-- 1 100000 100000    0 Feb 11 00:17 AAAA[K
drwxr-xr-x 1 100000 100000    0 Feb 11 00:17 [34m[1mBBBB(B[m[K
lrwxrwxrwx 1 100000 100000    7 Jul 25  2019 [36m[1mbin(B[m -> [34m[1musr/bin(B[m[K
dr-xr-xr-x 1 100000 100000    0 Jul 25  2019 [34m[1mboot(B[m[K
drwxr-xr-x 1 100000 100000    0 Feb 10 20:39 [34m[1mdev(B[m[K
drwxr-xr-x 1 100000 100000 2086 Feb 11 00:16 [34m[1metc(B[m[K
drwxr-xr-x 1 100000 100000    0 Jul 25  2019 [34m[1mhome(B[m[K
lrwxrwxrwx 1 100000 100000    7 Jul 25  2019 [36m[1mlib(B[m -> [34m[1musr/lib(B[m[K
lrwxrwxrwx 1 100000 100000    9 Jul 25  2019 [36m[1mlib64(B[m -> [34m[1musr/lib64(B[m[K
drwx------ 1 100000 100000    0 Feb 10 05:47 [34m[1mlost+found(B[m[K
drwxr-xr-x 1 100000 100000    0 Jul 25  2019 [34m[1mmedia(B[m[K
drwxr-xr-x 1 100000 100000    0 Jul 25  2019 [34m[1mmnt(B[m[K
drwxr-xr-x 1 100000 100000    0 Jul 25  2019 [34m[1mopt(B[m[K
drwxr-xr-x 1 100000 100000    0 Feb 10 05:47 [34m[1mproc(B[m[K
dr-xr-x--- 1 100000 100000   90 Feb 11 00:17 [34m[1mroot(B[m[K
drwxr-xr-x 1 100000 100000  152 Feb 10 05:48 [34m[1mrun(B[m[K
lrwxrwxrwx 1 100000 100000    8 Jul 25  2019 [36m[1msbin(B[m -> [34m[1musr/sbin(B[m[K
drwxr-xr-x 1 100000 100000    0 Jul 25  2019 [34m[1msrv(B[m[K
drwxr-xr-x 1 100000 100000    0 Feb 10 05:47 [34m[1msys(B[m[K
drwxrwxrwt 1 100000 100000    0 Feb 10 20:33 [30m[42mtmp[39m[49m[K
drwxr-xr-x 1 100000 100000  100 Feb 10 05:47 [34m[1musr(B[m[K
drwxr-xr-x 1 100000 100000  170 Feb 11 00:16 [34m[1mvar(B[m[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # So container runtimes don't need to care about fsid mappings if they don't want[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[28;15H[?12l[?25h# or need to.[2;28r[28;1H
[1;28r[28;1H[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[2;1Hd--x------ 1 100000 root     78 Feb 11 00:16 [34m[1m..(B[m[K
-rw-r--r-- 1 100000 100000    0 Feb 11 00:16 .autorelabel[K
-rw-r--r-- 1 100000 100000    0 Feb 11 00:17 AAAA[K
drwxr-xr-x 1 100000 100000    0 Feb 11 00:17 [34m[1mBBBB(B[m[K
lrwxrwxrwx 1 100000 100000    7 Jul 25  2019 [36m[1mbin(B[m -> [34m[1musr/bin(B[m[K
dr-xr-xr-x 1 100000 100000    0 Jul 25  2019 [34m[1mboot(B[m[K
drwxr-xr-x 1 100000 100000    0 Feb 10 20:39 [34m[1mdev(B[m[K
drwxr-xr-x 1 100000 100000 2086 Feb 11 00:16 [34m[1metc(B[m[K
drwxr-xr-x 1 100000 100000    0 Jul 25  2019 [34m[1mhome(B[m[K
lrwxrwxrwx 1 100000 100000    7 Jul 25  2019 [36m[1mlib(B[m -> [34m[1musr/lib(B[m[K
lrwxrwxrwx 1 100000 100000    9 Jul 25  2019 [36m[1mlib64(B[m -> [34m[1musr/lib64(B[m[K
drwx------ 1 100000 100000    0 Feb 10 05:47 [34m[1mlost+found(B[m[K
drwxr-xr-x 1 100000 100000    0 Jul 25  2019 [34m[1mmedia(B[m[K
drwxr-xr-x 1 100000 100000    0 Jul 25  2019 [34m[1mmnt(B[m[K
drwxr-xr-x 1 100000 100000    0 Jul 25  2019 [34m[1mopt(B[m[K
drwxr-xr-x 1 100000 100000    0 Feb 10 05:47 [34m[1mproc(B[m[K
dr-xr-x--- 1 100000 100000   90 Feb 11 00:17 [34m[1mroot(B[m[K
drwxr-xr-x 1 100000 100000  152 Feb 10 05:48 [34m[1mrun(B[m[K
lrwxrwxrwx 1 100000 100000    8 Jul 25  2019 [36m[1msbin(B[m -> [34m[1musr/sbin(B[m[K
drwxr-xr-x 1 100000 100000    0 Jul 25  2019 [34m[1msrv(B[m[K
drwxr-xr-x 1 100000 100000    0 Feb 10 05:47 [34m[1msys(B[m[K
drwxrwxrwt 1 100000 100000    0 Feb 10 20:33 [30m[42mtmp[39m[49m[K
drwxr-xr-x 1 100000 100000  100 Feb 10 05:47 [34m[1musr(B[m[K
drwxr-xr-x 1 100000 100000  170 Feb 11 00:16 [34m[1mvar(B[m[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # So container runtimes don't need to care about fsid mappings if they don't want[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # or need to.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[28;15H[?12l[?25h[1;28r(B[m[?1l>[H[2J]112[?12l[?25h[?1000l[?1002l[?1006l[?1005l[detached (from session demo)]
[0;32m[0m[1;34mbrauner[1;37m@[1;33mwittgenstein[1;37m|[1;33m~/src/git/cground/shiftfs_fsid_perf[1;32m[1;37m|[1;36mgithub-master %=
[0m[1;34m>[0m[0;32m[0m exit

Script done on 2020-02-12 12:44:34+01:00 [COMMAND_EXIT_CODE="0"]
