Script started on 2020-02-12 12:38:29+01:00 [TERM="xterm-256color" TTY="/dev/pts/31" COLUMNS="240" LINES="28"]
[0;32m[0m[1;34mbrauner[1;37m@[1;33mwittgenstein[1;37m|[1;33m~/src/git/cground/shiftfs_fsid_perf[1;32m[1;37m|[1;36mgithub-master %=
[0m[1;34m>[0m[0;32m[0m asciinema plad[Ky demo3.play 
[?1h=[H[2J[?12l[?25h[?1000l[?1002l[?1006l[?1005l[c(B[m[?12;25h[?12l[?25h[?1003l[?1006l[?2004l[1;1H[1;28r]112[2;15H[?1006h[?1002h[?25l[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[2;15H[?12l[?25h(B[m[?12;25h[?12l[?25h[?1003l[?1006l[?2004l[1;1H[1;28r[2;15H[?1006h[?1002h[?25l[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[2;15H[?12l[?25h# We want to share dedictated storage with multiple containers.
[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[32m[1m[2;1Hroot@e1-vm(B[m:[34m[1m~(B[m# # We want to share dedictated storage with multiple containers.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[3;15H[?12l[?25h# This is often usedn[K when sharing large datasets among ocntai[K[K[K[K[K[Kcontainers.
[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[32m[1m[2;1Hroot@e1-vm(B[m:[34m[1m~(B[m# # We want to share dedictated storage with multiple containers.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # This is often used when sharing large datasets among containers.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[4;15H[?12l[?25h# For example, when  [Kperforming calculations and writee[K a[Kback results to the shared storage.
[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[32m[1m[2;1Hroot@e1-vm(B[m:[34m[1m~(B[m# # We want to share dedictated storage with multiple containers.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # This is often used when sharing large datasets among containers.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # For example, when performing calculations and write back results to the shared storage.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[5;15H[?12l[?25h
[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[32m[1m[2;1Hroot@e1-vm(B[m:[34m[1m~(B[m# # We want to share dedictated storage with multiple containers.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # This is often used when sharing large datasets among containers.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # For example, when performing calculations and write back results to the shared storage.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[6;15H[?12l[?25h# For extra security we want all containers to have different id mappings.
[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[32m[1m[2;1Hroot@e1-vm(B[m:[34m[1m~(B[m# # We want to share dedictated storage with multiple containers.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # This is often used when sharing large datasets among containers.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # For example, when performing calculations and write back results to the shared storage.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # For extra security we want all containers to have different id mappings.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[7;15H[?12l[?25h# To this end we set the security i[K[K.idmap.isolated property.
[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[32m[1m[2;1Hroot@e1-vm(B[m:[34m[1m~(B[m# # We want to share dedictated storage with multiple containers.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # This is often used when sharing large datasets among containers.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # For example, when performing calculations and write back results to the shared storage.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # For extra security we want all containers to have different id mappings.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # To this end we set the security.idmap.isolated property.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[8;15H[?12l[?25h
[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[32m[1m[2;1Hroot@e1-vm(B[m:[34m[1m~(B[m# # We want to share dedictated storage with multiple containers.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # This is often used when sharing large datasets among containers.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # For example, when performing calculations and write back results to the shared storage.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # For extra security we want all containers to have different id mappings.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # To this end we set the security.idmap.isolated property.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[9;15H[?12l[?25hlxc profile set default security[?25l[32m[1m[2;1Hroot@e1-vm(B[m:[34m[1m~(B[m# # We want to share dedictated storage with multiple containers.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # This is often used when sharing large datasets among containers.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # For example, when performing calculations and write back results to the shared storage.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # For extra security we want all containers to have different id mappings.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # To this end we set the security.idmap.isolated property.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc profile set default security[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[9;47H[?12l[?25h.idmap.isolated true
[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[32m[1m[2;1Hroot@e1-vm(B[m:[34m[1m~(B[m# # We want to share dedictated storage with multiple containers.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # This is often used when sharing large datasets among containers.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # For example, when performing calculations and write back results to the shared storage.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # For extra security we want all containers to have different id mappings.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # To this end we set the security.idmap.isolated property.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc profile set default security.idmap.isolated true[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[10;15H[?12l[?25h
[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[32m[1m[2;1Hroot@e1-vm(B[m:[34m[1m~(B[m# # We want to share dedictated storage with multiple containers.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # This is often used when sharing large datasets among containers.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # For example, when performing calculations and write back results to the shared storage.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # For extra security we want all containers to have different id mappings.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # To this end we set the security.idmap.isolated property.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc profile set default security.idmap.isolated true[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[11;15H[?12l[?25h# n[KNow e[Kwe launch three containers. Allf o[K[K[K of them will have s[Kisolated id mappings:
[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[32m[1m[2;1Hroot@e1-vm(B[m:[34m[1m~(B[m# # We want to share dedictated storage with multiple containers.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # This is often used when sharing large datasets among containers.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # For example, when performing calculations and write back results to the shared storage.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # For extra security we want all containers to have different id mappings.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # To this end we set the security.idmap.isolated property.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc profile set default security.idmap.isolated true[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # Now we launch three containers. All of them will have isolated id mappings:[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[12;15H[?12l[?25hlxc launch images:fedora/1[K31 fed1
Creating fed1
Starting fed1
[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[32m[1m[2;1Hroot@e1-vm(B[m:[34m[1m~(B[m# # We want to share dedictated storage with multiple containers.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # This is often used when sharing large datasets among containers.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # For example, when performing calculations and write back results to the shared storage.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # For extra security we want all containers to have different id mappings.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # To this end we set the security.idmap.isolated property.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc profile set default security.idmap.isolated true[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # Now we launch three containers. All of them will have isolated id mappings:[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc launch images:fedora/31 fed1[K
Creating fed1[K
Starting fed1[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[15;15H[?12l[?25hlxc launch images:ubuntu/cofal [K[K[K[K[K[Kfocal f1
Creating f1
Starting f1
[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[32m[1m[2;1Hroot@e1-vm(B[m:[34m[1m~(B[m# # We want to share dedictated storage with multiple containers.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # This is often used when sharing large datasets among containers.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # For example, when performing calculations and write back results to the shared storage.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # For extra security we want all containers to have different id mappings.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # To this end we set the security.idmap.isolated property.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc profile set default security.idmap.isolated true[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # Now we launch three containers. All of them will have isolated id mappings:[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc launch images:fedora/31 fed1[K
Creating fed1[K
Starting fed1[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc launch images:ubuntu/focal f1[K
Creating f1[K
Starting f1[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[18;15H[?12l[?25hlxc launch images:opensuse/tumbleweed o1
Creating o1
Starting o1
[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[32m[1m[2;1Hroot@e1-vm(B[m:[34m[1m~(B[m# # We want to share dedictated storage with multiple containers.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # This is often used when sharing large datasets among containers.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # For example, when performing calculations and write back results to the shared storage.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # For extra security we want all containers to have different id mappings.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # To this end we set the security.idmap.isolated property.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc profile set default security.idmap.isolated true[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # Now we launch three containers. All of them will have isolated id mappings:[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc launch images:fedora/31 fed1[K
Creating fed1[K
Starting fed1[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc launch images:ubuntu/focal f1[K
Creating f1[K
Starting f1[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc launch images:opensuse/tumbleweed o1[K
Creating o1[K
Starting o1[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[21;15H[?12l[?25hclear
[2;28r[2;1H[J[1;28r[2;1H[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[2;15H[?12l[?25hlxc list
+------+---------+-----------------------+-----------------------------------------------+-----------+-----------+
| NAME |  STATE  |         IPV4          |                     IPV6                      |   TYPE    | SNAPSHOTS |
+------+---------+-----------------------+-----------------------------------------------+-----------+-----------+
| f1   | RUNNING |                       | fd42:2f90:857a:b195:216:3eff:fe42:eae8 (eth0) | CONTAINER | 0         |
+------+---------+-----------------------+-----------------------------------------------+-----------+-----------+
| fed1 | RUNNING | 10.178.168.145 (eth0) | fd42:2f90:857a:b195:216:3eff:feae:efe9 (eth0) | CONTAINER | 0         |
+------+---------+-----------------------+-----------------------------------------------+-----------+-----------+
| o1   | RUNNING | 10.178.168.233 (eth0) | fd42:2f90:857a:b195:216:3eff:fe47:34fb (eth0) | CONTAINER | 0         |
+------+---------+-----------------------+-----------------------------------------------+-----------+-----------+
[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[32m[1m[2;1Hroot@e1-vm(B[m:[34m[1m~(B[m# lxc list[K
+------+---------+-----------------------+-----------------------------------------------+-----------+-----------+[K
| NAME |  STATE  |         IPV4          |                     IPV6                      |   TYPE    | SNAPSHOTS |[K
+------+---------+-----------------------+-----------------------------------------------+-----------+-----------+[K
| f1   | RUNNING |                       | fd42:2f90:857a:b195:216:3eff:fe42:eae8 (eth0) | CONTAINER | 0         |[K
+------+---------+-----------------------+-----------------------------------------------+-----------+-----------+[K
| fed1 | RUNNING | 10.178.168.145 (eth0) | fd42:2f90:857a:b195:216:3eff:feae:efe9 (eth0) | CONTAINER | 0         |[K
+------+---------+-----------------------+-----------------------------------------------+-----------+-----------+[K
| o1   | RUNNING | 10.178.168.233 (eth0) | fd42:2f90:857a:b195:216:3eff:fe47:34fb (eth0) | CONTAINER | 0         |[K
+------+---------+-----------------------+-----------------------------------------------+-----------+-----------+[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[12;15H[?12l[?25hclear
[2;28r[2;1H[J[1;28r[2;1H[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[2;15H[?12l[?25h[1;28r(B[m[?1l>[H[2J]112[?12l[?25h[?1000l[?1002l[?1006l[?1005l[detached (from session demo)]
[?1h=[H[2J[?12l[?25h[?1000l[?1002l[?1006l[?1005l[c(B[m[?12;25h[?12l[?25h[?1003l[?1006l[?2004l[1;1H[1;28r]112[2;15H[?1006h[?1002h[?25l[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[2;15H[?12l[?25h(B[m[?12;25h[?12l[?25h[?1003l[?1006l[?2004l[1;1H[1;28r[2;15H[?1006h[?1002h[?25l[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[2;15H[?12l[?25h# Let's verify that they all have the same id mapping:
[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[32m[1m[2;1Hroot@e1-vm(B[m:[34m[1m~(B[m# # Let's verify that they all have the same id mapping:[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[3;15H[?12l[?25hlxc exec f1 -- cat /proc/self/{uid,gid{_[K[K}_map
         0     231072      65536
         0     231072      65536
[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[32m[1m[2;1Hroot@e1-vm(B[m:[34m[1m~(B[m# # Let's verify that they all have the same id mapping:[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec f1 -- cat /proc/self/{uid,gid}_map[K
         0     231072      65536[K
         0     231072      65536[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[6;15H[?12l[?25hlxc exec f1 -- cat /proc/self/{uid,gid}_map[1@e[1@d
         0     165536      65536
         0     165536      65536
[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[32m[1m[2;1Hroot@e1-vm(B[m:[34m[1m~(B[m# # Let's verify that they all have the same id mapping:[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec f1 -- cat /proc/self/{uid,gid}_map[K
         0     231072      65536[K
         0     231072      65536[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec fed1 -- cat /proc/self/{uid,gid}_map[K
         0     165536      65536[K
         0     165536      65536[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[9;15H[?12l[?25hlxc exec fed1 -- cat /proc/self/{uid,gid}_map[1P[1P[1P[1@o
         0     296608      65536
         0     296608      65536
[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[32m[1m[2;1Hroot@e1-vm(B[m:[34m[1m~(B[m# # Let's verify that they all have the same id mapping:[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec f1 -- cat /proc/self/{uid,gid}_map[K
         0     231072      65536[K
         0     231072      65536[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec fed1 -- cat /proc/self/{uid,gid}_map[K
         0     165536      65536[K
         0     165536      65536[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec o1 -- cat /proc/self/{uid,gid}_map[K
         0     296608      65536[K
         0     296608      65536[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[12;15H[?12l[?25h# Yep, that's true.
[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[32m[1m[2;1Hroot@e1-vm(B[m:[34m[1m~(B[m# # Let's verify that they all have the same id mapping:[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec f1 -- cat /proc/self/{uid,gid}_map[K
         0     231072      65536[K
         0     231072      65536[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec fed1 -- cat /proc/self/{uid,gid}_map[K
         0     165536      65536[K
         0     165536      65536[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec o1 -- cat /proc/self/{uid,gid}_map[K
         0     296608      65536[K
         0     296608      65536[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # Yep, that's true.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[13;15H[?12l[?25h# Let's verify that they all have the _same_ fsid mapping.
[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[32m[1m[2;1Hroot@e1-vm(B[m:[34m[1m~(B[m# # Let's verify that they all have the same id mapping:[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec f1 -- cat /proc/self/{uid,gid}_map[K
         0     231072      65536[K
         0     231072      65536[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec fed1 -- cat /proc/self/{uid,gid}_map[K
         0     165536      65536[K
         0     165536      65536[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec o1 -- cat /proc/self/{uid,gid}_map[K
         0     296608      65536[K
         0     296608      65536[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # Yep, that's true.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # Let's verify that they all have the _same_ fsid mapping.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[14;15H[?12l[?25h# Let's verify that they all have the _same_ fsid mapping.[17GYep, that's true.[K[15Glxc exec o1 -- cat /proc/self/{uid,gid}_map[24G[2@fed[33C[24G[2Po[33Cf{uid,gid}_map[13Ds{uid,gid}_map[13D
         0     300000     100000
         0     300000     100000
[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[32m[1m[2;1Hroot@e1-vm(B[m:[34m[1m~(B[m# # Let's verify that they all have the same id mapping:[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec f1 -- cat /proc/self/{uid,gid}_map[K
         0     231072      65536[K
         0     231072      65536[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec fed1 -- cat /proc/self/{uid,gid}_map[K
         0     165536      65536[K
         0     165536      65536[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec o1 -- cat /proc/self/{uid,gid}_map[K
         0     296608      65536[K
         0     296608      65536[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # Yep, that's true.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # Let's verify that they all have the _same_ fsid mapping.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec o1 -- cat /proc/self/fs{uid,gid}_map[K
         0     300000     100000[K
         0     300000     100000[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[17;15H[?12l[?25hlxc exec o1 -- cat /proc/self/fs{uid,gid}_map[1P[1@f
         0     300000     100000
         0     300000     100000
[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[32m[1m[2;1Hroot@e1-vm(B[m:[34m[1m~(B[m# # Let's verify that they all have the same id mapping:[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec f1 -- cat /proc/self/{uid,gid}_map[K
         0     231072      65536[K
         0     231072      65536[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec fed1 -- cat /proc/self/{uid,gid}_map[K
         0     165536      65536[K
         0     165536      65536[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec o1 -- cat /proc/self/{uid,gid}_map[K
         0     296608      65536[K
         0     296608      65536[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # Yep, that's true.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # Let's verify that they all have the _same_ fsid mapping.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec o1 -- cat /proc/self/fs{uid,gid}_map[K
         0     300000     100000[K
         0     300000     100000[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec f1 -- cat /proc/self/fs{uid,gid}_map[K
         0     300000     100000[K
         0     300000     100000[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[20;15H[?12l[?25hlxc exec f1 -- cat /proc/self/fs{uid,gid}_map[1@e[1@d
         0     300000     100000
         0     300000     100000
[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[32m[1m[2;1Hroot@e1-vm(B[m:[34m[1m~(B[m# # Let's verify that they all have the same id mapping:[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec f1 -- cat /proc/self/{uid,gid}_map[K
         0     231072      65536[K
         0     231072      65536[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec fed1 -- cat /proc/self/{uid,gid}_map[K
         0     165536      65536[K
         0     165536      65536[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec o1 -- cat /proc/self/{uid,gid}_map[K
         0     296608      65536[K
         0     296608      65536[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # Yep, that's true.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # Let's verify that they all have the _same_ fsid mapping.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec o1 -- cat /proc/self/fs{uid,gid}_map[K
         0     300000     100000[K
         0     300000     100000[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec f1 -- cat /proc/self/fs{uid,gid}_map[K
         0     300000     100000[K
         0     300000     100000[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec fed1 -- cat /proc/self/fs{uid,gid}_map[K
         0     300000     100000[K
         0     300000     100000[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[23;15H[?12l[?25h# Yep, that's also true
[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[32m[1m[2;1Hroot@e1-vm(B[m:[34m[1m~(B[m# # Let's verify that they all have the same id mapping:[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec f1 -- cat /proc/self/{uid,gid}_map[K
         0     231072      65536[K
         0     231072      65536[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec fed1 -- cat /proc/self/{uid,gid}_map[K
         0     165536      65536[K
         0     165536      65536[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec o1 -- cat /proc/self/{uid,gid}_map[K
         0     296608      65536[K
         0     296608      65536[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # Yep, that's true.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # Let's verify that they all have the _same_ fsid mapping.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec o1 -- cat /proc/self/fs{uid,gid}_map[K
         0     300000     100000[K
         0     300000     100000[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec f1 -- cat /proc/self/fs{uid,gid}_map[K
         0     300000     100000[K
         0     300000     100000[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec fed1 -- cat /proc/self/fs{uid,gid}_map[K
         0     300000     100000[K
         0     300000     100000[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # Yep, that's also true[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[24;15H[?12l[?25hclera
[2;28r[4S[22dCommand 'clera' not found, did you mean:[24;1H  command 'clear' from deb ncurses-bin (6.1+20190803-1ubuntu1)[26;1HTry: apt install <deb name>[1;28r[28;1H[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[32m[1m[2;1Hroot@e1-vm(B[m:[34m[1m~(B[m# lxc exec fed1 -- cat /proc/self/{uid,gid}_map[K
         0     165536      65536[K
         0     165536      65536[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec o1 -- cat /proc/self/{uid,gid}_map[K
         0     296608      65536[K
         0     296608      65536[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # Yep, that's true.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # Let's verify that they all have the _same_ fsid mapping.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec o1 -- cat /proc/self/fs{uid,gid}_map[K
         0     300000     100000[K
         0     300000     100000[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec f1 -- cat /proc/self/fs{uid,gid}_map[K
         0     300000     100000[K
         0     300000     100000[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec fed1 -- cat /proc/self/fs{uid,gid}_map[K
         0     300000     100000[K
         0     300000     100000[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # Yep, that's also true[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# clera[K
[K
Command 'clera' not found, did you mean:[K
[K
  command 'clear' from deb ncurses-bin (6.1+20190803-1ubuntu1)[K
[K
Try: apt install <deb name>[K
[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[28;15H[?12l[?25hclear[2;28r[28;1H
[1;28r[28;1H[2;28r[2;1H[J[1;28r[2;1H[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[2;15H[?12l[?25h# Now we want to share a git repository between all three containers and have them write to it.
[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[32m[1m[2;1Hroot@e1-vm(B[m:[34m[1m~(B[m# # Now we want to share a git repository between all three containers and have them write to it.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[3;15H[?12l[?25hls -al /srv/qemu/
total 2684
drwxr-xr-x 53 300000 300000   4096 Feb 11 16:18 [34m[1m.
(B[mdrwxr-xr-x  3 root   root     4096 Feb 11 15:53 [34m[1m..(B[m
-rw-r--r--  1 300000 300000   1101 Feb 11 15:54 .cirrus.yml
-rw-r--r--  1 300000 300000     75 Feb 11 15:54 .dir-locals.el
-rw-r--r--  1 300000 300000    748 Feb 11 15:54 .editorconfig
-rw-r--r--  1 300000 300000    220 Feb 11 15:54 .exrc
-rw-r--r--  1 300000 300000    326 Feb 11 15:54 .gdbinit
drwxr-xr-x  8 300000 300000   4096 Feb 11 15:54 [34m[1m.git
(B[m-rw-r--r--  1 300000 300000   3136 Feb 11 15:54 .gitignore
-rw-r--r--  1 300000 300000   1657 Feb 11 15:54 .gitlab-ci-edk2.yml
drwxr-xr-x  3 300000 300000   4096 Feb 11 15:54 [34m[1m.gitlab-ci.d
(B[m-rw-r--r--  1 300000 300000   3954 Feb 11 15:54 .gitlab-ci.yml
-rw-r--r--  1 300000 300000   1945 Feb 11 15:54 .gitmodules
-rw-r--r--  1 300000 300000   1650 Feb 11 15:54 .gitpublish
-rw-r--r--  1 300000 300000   7362 Feb 11 15:54 .mailmap
-rw-r--r--  1 300000 300000   8601 Feb 11 15:54 .patchew.yml
-rw-r--r--  1 300000 300000    543 Feb 11 15:54 .readthedocs.yml
-rw-r--r--  1 300000 300000   1309 Feb 11 15:54 .shippable.yml
-rw-r--r--  1 300000 300000  17068 Feb 11 15:54 .travis.yml
-rw-r--r--  1 300000 300000  21518 Feb 11 15:54 CODING_STYLE.rst
-rw-r--r--  1 300000 300000  17992 Feb 11 15:54 COPYING
-rw-r--r--  1 300000 300000  26530 Feb 11 15:54 COPYING.LIB
-rw-r--r--  1 300000 300000  23143 Feb 11 15:54 Changelog
[2;28r[28;1H
[A-rw-r--r--  1 300000 300000    511 Feb 11 15:54 Kconfig.host
-rw-r--r--  1 300000 300000   1177 Feb 11 15:54 LICENSE[1;28r[28;56H[2;28r[28;1H
[1;28r[28;1H[2;28r[2S[26d-rw-r--r--  1 300000 300000  61647 Feb 11 15:54 MAINTAINERS
-rw-r--r--  1 300000 300000  45961 Feb 11 15:54 Makefile[1;28r[28;1H[2;28r[2S[26d-rw-r--r--  1 300000 300000   6302 Feb 11 15:54 Makefile.objs
-rw-r--r--  1 300000 300000   7514 Feb 11 15:54 Makefile.target[1;28r[28;1H[2;28r[28;1H
[A-rw-r--r--  1 300000 300000   4936 Feb 11 15:54 README.rst[1;28r[28;1H[2;28r[10S[18d-rw-r--r--  1 300000 300000      7 Feb 11 15:54 VERSION
drwxr-xr-x  5 300000 300000   4096 Feb 11 15:54 [34m[1maccel
(B[m-rw-r--r--  1 300000 300000   3235 Feb 11 15:54 arch_init.c
drwxr-xr-x  2 300000 300000   4096 Feb 11 15:54 [34m[1maudio
(B[mdrwxr-xr-x  2 300000 300000   4096 Feb 11 15:54 [34m[1mauthz
(B[mdrwxr-xr-x  2 300000 300000   4096 Feb 11 15:54 [34m[1mbackends
(B[m-rw-r--r--  1 300000 300000   3582 Feb 11 15:54 balloon.c
drwxr-xr-x  2 300000 300000   4096 Feb 11 15:54 [34m[1mblock
(B[m-rw-r--r--  1 300000 300000 203847 Feb 11 15:54 block.c
-rw-r--r--  1 300000 300000   6763 Feb 11 15:54 blockdev-nbd.c
-rw-r--r--  1 300000 300000 143069 Feb 11 15:54 blockdev.c[1;28r[28;59H[2;28r[4S[25d-rw-r--r--  1 300000 300000  15589 Feb 11 15:54 blockjob.c
-rw-r--r--  1 300000 300000  11534 Feb 11 15:54 bootdevice.c
drwxr-xr-x  9 300000 300000   4096 Feb 11 15:54 [34m[1mbsd-user
(B[mdrwxr-xr-x  2 300000 300000   4096 Feb 11 15:54 [34m[1mcapstone[1;28r[28;57H(B[m[2;28r[5S[24ddrwxr-xr-x  2 300000 300000   4096 Feb 11 15:54 [34m[1mchardev
(B[m-rwxr-xr-x  1 300000 300000 215409 Feb 11 15:54 [32m[1mconfigure
(B[mdrwxr-xr-x 13 300000 300000   4096 Feb 11 15:54 [34m[1mcontrib
(B[m-rw-r--r--  1 300000 300000  10313 Feb 11 15:54 cpus-common.c[1;28r[28;1H[2;28r[3S[25d-rw-r--r--  1 300000 300000  62673 Feb 11 15:54 cpus.c
drwxr-xr-x  2 300000 300000   4096 Feb 11 15:54 [34m[1mcrypto
(B[mdrwxr-xr-x  2 300000 300000   4096 Feb 11 15:54 [34m[1mdefault-configs[1;28r[28;1H(B[m[2;28r[3S[25d-rw-r--r--  1 300000 300000   2615 Feb 11 15:54 device-hotplug.c
-rw-r--r--  1 300000 300000  14904 Feb 11 15:54 device_tree.c
drwxr-xr-x  3 300000 300000   4096 Feb 11 15:54 [34m[1mdisas[1;28r[28;1H(B[m[2;28r[17S[11d-rw-r--r--  1 300000 300000  21166 Feb 11 15:54 disas.c
-rw-r--r--  1 300000 300000   8245 Feb 11 15:54 dma-helpers.c
drwxr-xr-x  9 300000 300000   4096 Feb 11 15:54 [34m[1mdocs
(B[mdrwxr-xr-x  2 300000 300000   4096 Feb 11 15:54 [34m[1mdtc
(B[mdrwxr-xr-x  2 300000 300000   4096 Feb 11 15:54 [34m[1mdump
(B[m-rw-r--r--  1 300000 300000   3633 Feb 11 15:54 exec-vary.c
-rw-r--r--  1 300000 300000 122924 Feb 11 15:54 exec.c
drwxr-xr-x  2 300000 300000   4096 Feb 11 15:54 [34m[1mfpu
(B[mdrwxr-xr-x  2 300000 300000   4096 Feb 11 15:54 [34m[1mfsdev
(B[mdrwxr-xr-x  2 300000 300000   4096 Feb 11 15:54 [34m[1mgdb-xml
(B[m-rw-r--r--  1 300000 300000  88419 Feb 11 15:54 gdbstub.c
-rw-r--r--  1 300000 300000   1575 Feb 11 15:54 gitdm.config
-rw-r--r--  1 300000 300000  20232 Feb 11 15:54 hmp-commands-info.hx
-rw-r--r--  1 300000 300000  57257 Feb 11 15:54 hmp-commands.hx
drwxr-xr-x 66 300000 300000   4096 Feb 11 15:54 [34m[1mhw
(B[mdrwxr-xr-x 24 300000 300000   4096 Feb 11 15:54 [34m[1minclude
(B[mdrwxr-xr-x  2 300000 300000   4096 Feb 11 15:54 [34m[1mio[1;28r[28;1H(B[m[2;28r[4S[24d-rw-r--r--  1 300000 300000   9173 Feb 11 15:54 ioport.c
-rw-r--r--  1 300000 300000  11195 Feb 11 15:54 iothread.c
-rw-r--r--  1 300000 300000   4675 Feb 11 15:54 job-qmp.c
-rw-r--r--  1 300000 300000  24091 Feb 11 15:54 job.c[1;28r[28;1H[2;28r[2S[26ddrwxr-xr-x  3 300000 300000   4096 Feb 11 15:54 [34m[1mlibdecnumber
(B[mdrwxr-xr-x 11 300000 300000   4096 Feb 11 15:54 [34m[1mlinux-headers[1;28r[28;1H(B[m[2;28r[28;1H
[Adrwxr-xr-x 25 300000 300000   4096 Feb 11 15:54 [34m[1mlinux-user
(B[m-rw-r--r--  1 300000 300000 102319 Feb 11 15:54 memory.c[1;28r[28;57H[2;28r[28;1H
[1;28r[28;1H[2;28r[27S[2d-rw-r--r--  1 300000 300000   3459 Feb 11 15:54 qemu-edid.c
-rw-r--r--  1 300000 300000   4942 Feb 11 15:54 qemu-img-cmds.hx
-rw-r--r--  1 300000 300000 152401 Feb 11 15:54 qemu-img.c
-rw-r--r--  1 300000 300000  65566 Feb 11 15:54 qemu-io-cmds.c
-rw-r--r--  1 300000 300000  18890 Feb 11 15:54 qemu-io.c
-rw-r--r--  1 300000 300000   7528 Feb 11 15:54 qemu-keymap.c
-rw-r--r--  1 300000 300000  35820 Feb 11 15:54 qemu-nbd.c
-rw-r--r--  1 300000 300000   1118 Feb 11 15:54 qemu-option-trace.texi
-rw-r--r--  1 300000 300000   1042 Feb 11 15:54 qemu-options-wrapper.h
-rw-r--r--  1 300000 300000   1401 Feb 11 15:54 qemu-options.h
-rw-r--r--  1 300000 300000 204778 Feb 11 15:54 qemu-options.hx
-rw-r--r--  1 300000 300000  11672 Feb 11 15:54 qemu-seccomp.c
-rw-r--r--  1 300000 300000   5466 Feb 11 15:54 qemu-tech.texi
-rw-r--r--  1 300000 300000   7589 Feb 11 15:54 qemu.nsi
-rw-r--r--  1 300000 300000   1795 Feb 11 15:54 qemu.sasl
drwxr-xr-x  4 300000 300000   4096 Feb 11 15:54 [34m[1mqga
(B[mdrwxr-xr-x  2 300000 300000   4096 Feb 11 15:54 [34m[1mqobject
(B[mdrwxr-xr-x  2 300000 300000   4096 Feb 11 15:54 [34m[1mqom
(B[m-rw-r--r--  1 300000 300000  22277 Feb 11 15:54 qtest.c
drwxr-xr-x  2 300000 300000   4096 Feb 11 15:54 [34m[1mreplay
(B[m-rw-r--r--  1 300000 300000   2524 Feb 11 15:54 replication.c
-rw-r--r--  1 300000 300000   5309 Feb 11 15:54 replication.h
drwxr-xr-x 16 300000 300000   4096 Feb 11 15:54 [34m[1mroms
(B[m-rw-r--r--  1 300000 300000  16533 Feb 11 15:54 rules.mak
drwxr-xr-x 11 300000 300000   4096 Feb 11 15:54 [34m[1mscripts
(B[mdrwxr-xr-x  2 300000 300000   4096 Feb 11 15:54 [34m[1mscsi
(B[mdrwxr-xr-x  2 300000 300000   4096 Feb 11 15:54 [34m[1mslirp[1;28r[28;54H(B[m[2;28r[11S[18ddrwxr-xr-x  2 300000 300000   4096 Feb 11 15:54 [34m[1mstubs
(B[mdrwxr-xr-x 23 300000 300000   4096 Feb 11 15:54 [34m[1mtarget
(B[mdrwxr-xr-x 11 300000 300000   4096 Feb 11 15:54 [34m[1mtcg
(B[mdrwxr-xr-x 22 300000 300000   4096 Feb 11 15:54 [34m[1mtests
(B[m-rw-r--r--  1 300000 300000   9307 Feb 11 15:54 thunk.c
drwxr-xr-x  3 300000 300000   4096 Feb 11 15:54 [34m[1mtools
(B[m-rw-r--r--  1 300000 300000   5578 Feb 11 15:54 tpm.c
drwxr-xr-x  2 300000 300000   4096 Feb 11 15:54 [34m[1mtrace
(B[m-rw-r--r--  1 300000 300000   7989 Feb 11 15:54 trace-events
drwxr-xr-x  5 300000 300000   4096 Feb 11 15:54 [34m[1mui[1;28r[28;1H(B[m[2;28r[3S[25ddrwxr-xr-x  2 300000 300000   4096 Feb 11 15:54 [34m[1mutil
(B[m-rw-r--r--  1 300000 300000    790 Feb 11 15:54 version.rc
-rw-r--r--  1 300000 300000 135378 Feb 11 15:54 vl.c[1;28r[28;1H[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[2;1H-rw-r--r--  1 300000 300000   1795 Feb 11 15:54 qemu.sasl[K
drwxr-xr-x  4 300000 300000   4096 Feb 11 15:54 [34m[1mqga(B[m[K
drwxr-xr-x  2 300000 300000   4096 Feb 11 15:54 [34m[1mqobject(B[m[K
drwxr-xr-x  2 300000 300000   4096 Feb 11 15:54 [34m[1mqom(B[m[K
-rw-r--r--  1 300000 300000  22277 Feb 11 15:54 qtest.c[K
drwxr-xr-x  2 300000 300000   4096 Feb 11 15:54 [34m[1mreplay(B[m[K
-rw-r--r--  1 300000 300000   2524 Feb 11 15:54 replication.c[K
-rw-r--r--  1 300000 300000   5309 Feb 11 15:54 replication.h[K
drwxr-xr-x 16 300000 300000   4096 Feb 11 15:54 [34m[1mroms(B[m[K
-rw-r--r--  1 300000 300000  16533 Feb 11 15:54 rules.mak[K
drwxr-xr-x 11 300000 300000   4096 Feb 11 15:54 [34m[1mscripts(B[m[K
drwxr-xr-x  2 300000 300000   4096 Feb 11 15:54 [34m[1mscsi(B[m[K
drwxr-xr-x  2 300000 300000   4096 Feb 11 15:54 [34m[1mslirp(B[m[K
drwxr-xr-x  2 300000 300000   4096 Feb 11 15:54 [34m[1mstubs(B[m[K
drwxr-xr-x 23 300000 300000   4096 Feb 11 15:54 [34m[1mtarget(B[m[K
drwxr-xr-x 11 300000 300000   4096 Feb 11 15:54 [34m[1mtcg(B[m[K
drwxr-xr-x 22 300000 300000   4096 Feb 11 15:54 [34m[1mtests(B[m[K
-rw-r--r--  1 300000 300000   9307 Feb 11 15:54 thunk.c[K
drwxr-xr-x  3 300000 300000   4096 Feb 11 15:54 [34m[1mtools(B[m[K
-rw-r--r--  1 300000 300000   5578 Feb 11 15:54 tpm.c[K
drwxr-xr-x  2 300000 300000   4096 Feb 11 15:54 [34m[1mtrace(B[m[K
-rw-r--r--  1 300000 300000   7989 Feb 11 15:54 trace-events[K
drwxr-xr-x  5 300000 300000   4096 Feb 11 15:54 [34m[1mui(B[m[K
drwxr-xr-x  2 300000 300000   4096 Feb 11 15:54 [34m[1mutil(B[m[K
-rw-r--r--  1 300000 300000    790 Feb 11 15:54 version.rc[K
-rw-r--r--  1 300000 300000 135378 Feb 11 15:54 vl.c[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[28;15H[?12l[?25h# This is the repository we a[Kant to [K[K[K[K[K[K[Kwant to share[2;28r[28;1H
[1;28r[28;1H[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# clear[2;28r[28;1H
[1;28r[28;1H[2;28r[2;1H[J[1;28r[2;1H[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[2;15H[?12l[?25h# The fsid mappings wil [Kl take care that a[Kthe resp[K[Kpository has the c[Kright mper[K[K[Kpe[K[K[Kpermissions in each container.
[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[32m[1m[2;1Hroot@e1-vm(B[m:[34m[1m~(B[m# # The fsid mappings will take care that the repository has the right permissions in each container.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[3;15H[?12l[?25h# Let's a[Khotplug the repository at /opr[Kt/qemu in the container, currently the'r[K[Kre's nothing
[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[32m[1m[2;1Hroot@e1-vm(B[m:[34m[1m~(B[m# # The fsid mappings will take care that the repository has the right permissions in each container.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # Let's hotplug the repository at /opt/qemu in the container, currently there's nothing[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[4;15H[?12l[?25hlxc exec f1 -- ls -al /opt/
total 0
drwxr-xr-x 1 root root   0 Feb 11 16:19 .
drwxr-xr-x 1 root root 154 Feb 11 15:11 ..
[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[32m[1m[2;1Hroot@e1-vm(B[m:[34m[1m~(B[m# # The fsid mappings will take care that the repository has the right permissions in each container.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # Let's hotplug the repository at /opt/qemu in the container, currently there's nothing[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec f1 -- ls -al /opt/[K
total 0[K
drwxr-xr-x 1 root root   0 Feb 11 16:19 .[K
drwxr-xr-x 1 root root 154 Feb 11 15:11 ..[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[8;15H[?12l[?25hlxc exec f1 -- ls -al /opt/[1@e[1@d
total 0
drwxr-xr-x 1 root root   0 Feb 11 16:19 .
dr-xr-xr-x 1 root root 152 Feb 11 15:11 ..
[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[32m[1m[2;1Hroot@e1-vm(B[m:[34m[1m~(B[m# # The fsid mappings will take care that the repository has the right permissions in each container.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # Let's hotplug the repository at /opt/qemu in the container, currently there's nothing[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec f1 -- ls -al /opt/[K
total 0[K
drwxr-xr-x 1 root root   0 Feb 11 16:19 .[K
drwxr-xr-x 1 root root 154 Feb 11 15:11 ..[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec fed1 -- ls -al /opt/[K
total 0[K
drwxr-xr-x 1 root root   0 Feb 11 16:19 .[K
dr-xr-xr-x 1 root root 152 Feb 11 15:11 ..[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[12;15H[?12l[?25hlxc exec fed1 -- ls -al /opt/[1P[1P[1P[1@o
total 0
drwxr-xr-x 1 root root   0 Feb 11 16:19 .
drwxr-xr-x 1 root root 136 Feb 11 15:11 ..
[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[32m[1m[2;1Hroot@e1-vm(B[m:[34m[1m~(B[m# # The fsid mappings will take care that the repository has the right permissions in each container.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # Let's hotplug the repository at /opt/qemu in the container, currently there's nothing[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec f1 -- ls -al /opt/[K
total 0[K
drwxr-xr-x 1 root root   0 Feb 11 16:19 .[K
drwxr-xr-x 1 root root 154 Feb 11 15:11 ..[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec fed1 -- ls -al /opt/[K
total 0[K
drwxr-xr-x 1 root root   0 Feb 11 16:19 .[K
dr-xr-xr-x 1 root root 152 Feb 11 15:11 ..[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec o1 -- ls -al /opt/[K
total 0[K
drwxr-xr-x 1 root root   0 Feb 11 16:19 .[K
drwxr-xr-x 1 root root 136 Feb 11 15:11 ..[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[16;15H[?12l[?25hlxc c[Kprofile device add default shared-storage disk source=/srv/qemu path=opt[K[K[K/opt/qemu
Device shared-storage added to default
[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[32m[1m[2;1Hroot@e1-vm(B[m:[34m[1m~(B[m# # The fsid mappings will take care that the repository has the right permissions in each container.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # Let's hotplug the repository at /opt/qemu in the container, currently there's nothing[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec f1 -- ls -al /opt/[K
total 0[K
drwxr-xr-x 1 root root   0 Feb 11 16:19 .[K
drwxr-xr-x 1 root root 154 Feb 11 15:11 ..[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec fed1 -- ls -al /opt/[K
total 0[K
drwxr-xr-x 1 root root   0 Feb 11 16:19 .[K
dr-xr-xr-x 1 root root 152 Feb 11 15:11 ..[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec o1 -- ls -al /opt/[K
total 0[K
drwxr-xr-x 1 root root   0 Feb 11 16:19 .[K
drwxr-xr-x 1 root root 136 Feb 11 15:11 ..[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc profile device add default shared-storage disk source=/srv/qemu path=/opt/qemu[K
Device shared-storage added to default[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[18;15H[?12l[?25h# This will have hotpluuged[K[K[K[Kgged the reps[Kositi[Kory
[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[32m[1m[2;1Hroot@e1-vm(B[m:[34m[1m~(B[m# # The fsid mappings will take care that the repository has the right permissions in each container.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # Let's hotplug the repository at /opt/qemu in the container, currently there's nothing[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec f1 -- ls -al /opt/[K
total 0[K
drwxr-xr-x 1 root root   0 Feb 11 16:19 .[K
drwxr-xr-x 1 root root 154 Feb 11 15:11 ..[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec fed1 -- ls -al /opt/[K
total 0[K
drwxr-xr-x 1 root root   0 Feb 11 16:19 .[K
dr-xr-xr-x 1 root root 152 Feb 11 15:11 ..[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec o1 -- ls -al /opt/[K
total 0[K
drwxr-xr-x 1 root root   0 Feb 11 16:19 .[K
drwxr-xr-x 1 root root 136 Feb 11 15:11 ..[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc profile device add default shared-storage disk source=/srv/qemu path=/opt/qemu[K
Device shared-storage added to default[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # This will have hotplugged the repository[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[19;15H[?12l[?25hclear
[2;28r[2;1H[J[1;28r[2;1H[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[2;15H[?12l[?25hclear[5D# This will have hotplugged the repository[15Glxc profile device add default shared-storage disk source=/srv/qemu path=/opt/qemu[19Gexec o1 -- ls -al /opt/[K
total 4
drwxr-xr-x  1 root root    8 Feb 11 16:22 .
drwxr-xr-x  1 root root  136 Feb 11 15:11 ..
drwxr-xr-x 53 root root 4096 Feb 11 16:18 qemu
[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[32m[1m[2;1Hroot@e1-vm(B[m:[34m[1m~(B[m# lxc exec o1 -- ls -al /opt/[K
total 4[K
drwxr-xr-x  1 root root    8 Feb 11 16:22 .[K
drwxr-xr-x  1 root root  136 Feb 11 15:11 ..[K
drwxr-xr-x 53 root root 4096 Feb 11 16:18 qemu[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[7;15H[?12l[?25hlxc exec o1 -- ls -al /opt/qemu/
[2;28r[27S[2d-rw-r--r--  1 root root   1177 Feb 11 15:54 LICENSE
-rw-r--r--  1 root root  61647 Feb 11 15:54 MAINTAINERS
-rw-r--r--  1 root root  45961 Feb 11 15:54 Makefile
-rw-r--r--  1 root root   6302 Feb 11 15:54 Makefile.objs
-rw-r--r--  1 root root   7514 Feb 11 15:54 Makefile.target
-rw-r--r--  1 root root   4936 Feb 11 15:54 README.rst
-rw-r--r--  1 root root      7 Feb 11 15:54 VERSION
drwxr-xr-x  5 root root   4096 Feb 11 15:54 accel
-rw-r--r--  1 root root   3235 Feb 11 15:54 arch_init.c
drwxr-xr-x  2 root root   4096 Feb 11 15:54 audio
drwxr-xr-x  2 root root   4096 Feb 11 15:54 authz
drwxr-xr-x  2 root root   4096 Feb 11 15:54 backends
-rw-r--r--  1 root root   3582 Feb 11 15:54 balloon.c
drwxr-xr-x  2 root root   4096 Feb 11 15:54 block
-rw-r--r--  1 root root 203847 Feb 11 15:54 block.c
-rw-r--r--  1 root root   6763 Feb 11 15:54 blockdev-nbd.c
-rw-r--r--  1 root root 143069 Feb 11 15:54 blockdev.c
-rw-r--r--  1 root root  15589 Feb 11 15:54 blockjob.c
-rw-r--r--  1 root root  11534 Feb 11 15:54 bootdevice.c
drwxr-xr-x  9 root root   4096 Feb 11 15:54 bsd-user
drwxr-xr-x  2 root root   4096 Feb 11 15:54 capstone
drwxr-xr-x  2 root root   4096 Feb 11 15:54 chardev
-rwxr-xr-x  1 root root 215409 Feb 11 15:54 configure
drwxr-xr-x 13 root root   4096 Feb 11 15:54 contrib
-rw-r--r--  1 root root  10313 Feb 11 15:54 cpus-common.c
-rw-r--r--  1 root root  62673 Feb 11 15:54 cpus.c[1;28r[28;1H[2;28r[27S[2d-rw-r--r--  1 root root  93723 Feb 11 15:54 qemu-doc.texi
-rw-r--r--  1 root root   3459 Feb 11 15:54 qemu-edid.c
-rw-r--r--  1 root root   4942 Feb 11 15:54 qemu-img-cmds.hx
-rw-r--r--  1 root root 152401 Feb 11 15:54 qemu-img.c
-rw-r--r--  1 root root  65566 Feb 11 15:54 qemu-io-cmds.c
-rw-r--r--  1 root root  18890 Feb 11 15:54 qemu-io.c
-rw-r--r--  1 root root   7528 Feb 11 15:54 qemu-keymap.c
-rw-r--r--  1 root root  35820 Feb 11 15:54 qemu-nbd.c
-rw-r--r--  1 root root   1118 Feb 11 15:54 qemu-option-trace.texi
-rw-r--r--  1 root root   1042 Feb 11 15:54 qemu-options-wrapper.h
-rw-r--r--  1 root root   1401 Feb 11 15:54 qemu-options.h
-rw-r--r--  1 root root 204778 Feb 11 15:54 qemu-options.hx
-rw-r--r--  1 root root  11672 Feb 11 15:54 qemu-seccomp.c
-rw-r--r--  1 root root   5466 Feb 11 15:54 qemu-tech.texi
-rw-r--r--  1 root root   7589 Feb 11 15:54 qemu.nsi
-rw-r--r--  1 root root   1795 Feb 11 15:54 qemu.sasl
drwxr-xr-x  4 root root   4096 Feb 11 15:54 qga
drwxr-xr-x  2 root root   4096 Feb 11 15:54 qobject
drwxr-xr-x  2 root root   4096 Feb 11 15:54 qom
-rw-r--r--  1 root root  22277 Feb 11 15:54 qtest.c
drwxr-xr-x  2 root root   4096 Feb 11 15:54 replay
-rw-r--r--  1 root root   2524 Feb 11 15:54 replication.c
-rw-r--r--  1 root root   5309 Feb 11 15:54 replication.h
drwxr-xr-x 16 root root   4096 Feb 11 15:54 roms
-rw-r--r--  1 root root  16533 Feb 11 15:54 rules.mak
drwxr-xr-x 11 root root   4096 Feb 11 15:54 scripts
drwxr-xr-x  2 root ro[1;28r[28;22H[2;28r[15S[13;22Hot   4096 Feb 11 15:54 scsi
drwxr-xr-x  2 root root   4096 Feb 11 15:54 slirp
drwxr-xr-x  2 root root   4096 Feb 11 15:54 stubs
drwxr-xr-x 23 root root   4096 Feb 11 15:54 target
drwxr-xr-x 11 root root   4096 Feb 11 15:54 tcg
drwxr-xr-x 22 root root   4096 Feb 11 15:54 tests
-rw-r--r--  1 root root   9307 Feb 11 15:54 thunk.c
drwxr-xr-x  3 root root   4096 Feb 11 15:54 tools
-rw-r--r--  1 root root   5578 Feb 11 15:54 tpm.c
drwxr-xr-x  2 root root   4096 Feb 11 15:54 trace
-rw-r--r--  1 root root   7989 Feb 11 15:54 trace-events
drwxr-xr-x  5 root root   4096 Feb 11 15:54 ui
drwxr-xr-x  2 root root   4096 Feb 11 15:54 util
-rw-r--r--  1 root root    790 Feb 11 15:54 version.rc
-rw-r--r--  1 root root 135378 Feb 11 15:54 vl.c[1;28r[28;1H[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[2;1H-rw-r--r--  1 root root   1795 Feb 11 15:54 qemu.sasl[K
drwxr-xr-x  4 root root   4096 Feb 11 15:54 qga[K
drwxr-xr-x  2 root root   4096 Feb 11 15:54 qobject[K
drwxr-xr-x  2 root root   4096 Feb 11 15:54 qom[K
-rw-r--r--  1 root root  22277 Feb 11 15:54 qtest.c[K
drwxr-xr-x  2 root root   4096 Feb 11 15:54 replay[K
-rw-r--r--  1 root root   2524 Feb 11 15:54 replication.c[K
-rw-r--r--  1 root root   5309 Feb 11 15:54 replication.h[K
drwxr-xr-x 16 root root   4096 Feb 11 15:54 roms[K
-rw-r--r--  1 root root  16533 Feb 11 15:54 rules.mak[K
drwxr-xr-x 11 root root   4096 Feb 11 15:54 scripts[K
drwxr-xr-x  2 root root   4096 Feb 11 15:54 scsi[K
drwxr-xr-x  2 root root   4096 Feb 11 15:54 slirp[K
drwxr-xr-x  2 root root   4096 Feb 11 15:54 stubs[K
drwxr-xr-x 23 root root   4096 Feb 11 15:54 target[K
drwxr-xr-x 11 root root   4096 Feb 11 15:54 tcg[K
drwxr-xr-x 22 root root   4096 Feb 11 15:54 tests[K
-rw-r--r--  1 root root   9307 Feb 11 15:54 thunk.c[K
drwxr-xr-x  3 root root   4096 Feb 11 15:54 tools[K
-rw-r--r--  1 root root   5578 Feb 11 15:54 tpm.c[K
drwxr-xr-x  2 root root   4096 Feb 11 15:54 trace[K
-rw-r--r--  1 root root   7989 Feb 11 15:54 trace-events[K
drwxr-xr-x  5 root root   4096 Feb 11 15:54 ui[K
drwxr-xr-x  2 root root   4096 Feb 11 15:54 util[K
-rw-r--r--  1 root root    790 Feb 11 15:54 version.rc[K
-rw-r--r--  1 root root 135378 Feb 11 15:54 vl.c[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[28;15H[?12l[?25hlxc exec o1 -- ls -al /opt/qemu/[1P[1@f[2;28r[28;1H
[1;28r[28;1H[2;28r[15S[13dtotal 2680
drwxr-xr-x 53 root root   4096 Feb 11 16:18 .
drwxr-xr-x  1 root root      8 Feb 11 16:22 ..
-rw-r--r--  1 root root   1101 Feb 11 15:54 .cirrus.yml
-rw-r--r--  1 root root     75 Feb 11 15:54 .dir-locals.el
-rw-r--r--  1 root root    748 Feb 11 15:54 .editorconfig
-rw-r--r--  1 root root    220 Feb 11 15:54 .exrc
-rw-r--r--  1 root root    326 Feb 11 15:54 .gdbinit
drwxr-xr-x  8 root root   4096 Feb 11 15:54 .git
-rw-r--r--  1 root root   3136 Feb 11 15:54 .gitignore
-rw-r--r--  1 root root   1657 Feb 11 15:54 .gitlab-ci-edk2.yml
drwxr-xr-x  3 root root   4096 Feb 11 15:54 .gitlab-ci.d
-rw-r--r--  1 root root   3954 Feb 11 15:54 .gitlab-ci.yml
-rw-r--r--  1 root root   1945 Feb 11 15:54 .gitmodules
-rw-r--r--  1 root root   1650 Feb 11 15:54 .gitpublish[1;28r[28;1H[2;28r[25S[3d-rw-r--r--  1 root root   7362 Feb 11 15:54 .mailmap
-rw-r--r--  1 root root   8601 Feb 11 15:54 .patchew.yml
-rw-r--r--  1 root root    543 Feb 11 15:54 .readthedocs.yml
-rw-r--r--  1 root root   1309 Feb 11 15:54 .shippable.yml
-rw-r--r--  1 root root  17068 Feb 11 15:54 .travis.yml
-rw-r--r--  1 root root  21518 Feb 11 15:54 CODING_STYLE.rst
-rw-r--r--  1 root root  17992 Feb 11 15:54 COPYING
-rw-r--r--  1 root root  26530 Feb 11 15:54 COPYING.LIB
-rw-r--r--  1 root root  23143 Feb 11 15:54 Changelog
-rw-r--r--  1 root root    511 Feb 11 15:54 Kconfig.host
-rw-r--r--  1 root root   1177 Feb 11 15:54 LICENSE
-rw-r--r--  1 root root  61647 Feb 11 15:54 MAINTAINERS
-rw-r--r--  1 root root  45961 Feb 11 15:54 Makefile
-rw-r--r--  1 root root   6302 Feb 11 15:54 Makefile.objs
-rw-r--r--  1 root root   7514 Feb 11 15:54 Makefile.target
-rw-r--r--  1 root root   4936 Feb 11 15:54 README.rst
-rw-r--r--  1 root root      7 Feb 11 15:54 VERSION
drwxr-xr-x  5 root root   4096 Feb 11 15:54 accel
-rw-r--r--  1 root root   3235 Feb 11 15:54 arch_init.c
drwxr-xr-x  2 root root   4096 Feb 11 15:54 audio
drwxr-xr-x  2 root root   4096 Feb 11 15:54 authz
drwxr-xr-x  2 root root   4096 Feb 11 15:54 backends
-rw-r--r--  1 root root   3582 Feb 11 15:54 balloon.c
drwxr-xr-x  2 root root   4096 Feb 11 15:54 block
-rw-r--r--  1 root root 203847 Feb 11 15:54 block.c
-rw-r--r--  1 root root   6763 Feb 11 15:54 blockdev-nbd.c[1;28r[28;59H[2;28r[27S[2d-rwxr-xr-x  1 root root 215409 Feb 11 15:54 configure
drwxr-xr-x 13 root root   4096 Feb 11 15:54 contrib
-rw-r--r--  1 root root  10313 Feb 11 15:54 cpus-common.c
-rw-r--r--  1 root root  62673 Feb 11 15:54 cpus.c
drwxr-xr-x  2 root root   4096 Feb 11 15:54 crypto
drwxr-xr-x  2 root root   4096 Feb 11 15:54 default-configs
-rw-r--r--  1 root root   2615 Feb 11 15:54 device-hotplug.c
-rw-r--r--  1 root root  14904 Feb 11 15:54 device_tree.c
drwxr-xr-x  3 root root   4096 Feb 11 15:54 disas
-rw-r--r--  1 root root  21166 Feb 11 15:54 disas.c
-rw-r--r--  1 root root   8245 Feb 11 15:54 dma-helpers.c
drwxr-xr-x  9 root root   4096 Feb 11 15:54 docs
drwxr-xr-x  2 root root   4096 Feb 11 15:54 dtc
drwxr-xr-x  2 root root   4096 Feb 11 15:54 dump
-rw-r--r--  1 root root   3633 Feb 11 15:54 exec-vary.c
-rw-r--r--  1 root root 122924 Feb 11 15:54 exec.c
drwxr-xr-x  2 root root   4096 Feb 11 15:54 fpu
drwxr-xr-x  2 root root   4096 Feb 11 15:54 fsdev
drwxr-xr-x  2 root root   4096 Feb 11 15:54 gdb-xml
-rw-r--r--  1 root root  88419 Feb 11 15:54 gdbstub.c
-rw-r--r--  1 root root   1575 Feb 11 15:54 gitdm.config
-rw-r--r--  1 root root  20232 Feb 11 15:54 hmp-commands-info.hx
-rw-r--r--  1 root root  57257 Feb 11 15:54 hmp-commands.hx
drwxr-xr-x 66 root root   4096 Feb 11 15:54 hw
drwxr-xr-x 24 root root   4096 Feb 11 15:54 include
drwxr-xr-x  2 root root   4096 Feb 11 15:54 io[1;28r[28;1H[2;28r[8S[20d-rw-r--r--  1 root root   9173 Feb 11 15:54 ioport.c
-rw-r--r--  1 root root  11195 Feb 11 15:54 iothread.c
-rw-r--r--  1 root root   4675 Feb 11 15:54 job-qmp.c
-rw-r--r--  1 root root  24091 Feb 11 15:54 job.c
drwxr-xr-x  3 root root   4096 Feb 11 15:54 libdecnumber
drwxr-xr-x 11 root root   4096 Feb 11 15:54 linux-headers
drwxr-xr-x 25 root root   4096 Feb 11 15:54 linux-user
-rw-r--r--  1 root root 102319 Feb 11 15:54 memory.c[1;28r[28;1H[2;28r[18S[10d-rw-r--r--  1 root root  15937 Feb 11 15:54 memory_ldst.inc.c
-rw-r--r--  1 root root  10803 Feb 11 15:54 memory_mapping.c
drwxr-xr-x  2 root root   4096 Feb 11 15:54 migration
-rw-r--r--  1 root root    113 Feb 11 15:54 module-common.c
drwxr-xr-x  2 root root   4096 Feb 11 15:54 monitor
drwxr-xr-x  2 root root   4096 Feb 11 15:54 nbd
drwxr-xr-x  3 root root   4096 Feb 11 15:54 net
-rw-r--r--  1 root root   8752 Feb 11 15:54 os-posix.c
-rw-r--r--  1 root root   2411 Feb 11 15:54 os-win32.c
drwxr-xr-x  6 root root   4096 Feb 11 15:54 pc-bios
drwxr-xr-x  2 root root   4096 Feb 11 15:54 plugins
drwxr-xr-x  2 root root   4096 Feb 11 15:54 po
drwxr-xr-x  3 root root   4096 Feb 11 15:54 python
drwxr-xr-x  2 root root   4096 Feb 11 15:54 qapi
-rw-r--r--  1 root root  27878 Feb 11 15:54 qdev-monitor.c
-rw-r--r--  1 root root  12018 Feb 11 15:54 qemu-bridge-helper.c
-rw-r--r--  1 root root  15976 Feb 11 15:54 qemu-deprecated.texi
-rw-r--r--  1 root root  93723 Feb 11 15:54 qemu-doc.texi[1;28r[28;1H[2;28r[27S[2d-rw-r--r--  1 root root  11672 Feb 11 15:54 qemu-seccomp.c
-rw-r--r--  1 root root   5466 Feb 11 15:54 qemu-tech.texi
-rw-r--r--  1 root root   7589 Feb 11 15:54 qemu.nsi
-rw-r--r--  1 root root   1795 Feb 11 15:54 qemu.sasl
drwxr-xr-x  4 root root   4096 Feb 11 15:54 qga
drwxr-xr-x  2 root root   4096 Feb 11 15:54 qobject
drwxr-xr-x  2 root root   4096 Feb 11 15:54 qom
-rw-r--r--  1 root root  22277 Feb 11 15:54 qtest.c
drwxr-xr-x  2 root root   4096 Feb 11 15:54 replay
-rw-r--r--  1 root root   2524 Feb 11 15:54 replication.c
-rw-r--r--  1 root root   5309 Feb 11 15:54 replication.h
drwxr-xr-x 16 root root   4096 Feb 11 15:54 roms
-rw-r--r--  1 root root  16533 Feb 11 15:54 rules.mak
drwxr-xr-x 11 root root   4096 Feb 11 15:54 scripts
drwxr-xr-x  2 root root   4096 Feb 11 15:54 scsi
drwxr-xr-x  2 root root   4096 Feb 11 15:54 slirp
drwxr-xr-x  2 root root   4096 Feb 11 15:54 stubs
drwxr-xr-x 23 root root   4096 Feb 11 15:54 target
drwxr-xr-x 11 root root   4096 Feb 11 15:54 tcg
drwxr-xr-x 22 root root   4096 Feb 11 15:54 tests
-rw-r--r--  1 root root   9307 Feb 11 15:54 thunk.c
drwxr-xr-x  3 root root   4096 Feb 11 15:54 tools
-rw-r--r--  1 root root   5578 Feb 11 15:54 tpm.c
drwxr-xr-x  2 root root   4096 Feb 11 15:54 trace
-rw-r--r--  1 root root   7989 Feb 11 15:54 trace-events
drwxr-xr-x  5 root root   4096 Feb 11 15:54 ui
drwxr-xr-[1;28r[28;10H[2;28r[3S[25;10Hx  2 root root   4096 Feb 11 15:54 util
-rw-r--r--  1 root root    790 Feb 11 15:54 version.rc
-rw-r--r--  1 root root 135378 Feb 11 15:54 vl.c[1;28r[28;1H[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[2;1H-rw-r--r--  1 root root   1795 Feb 11 15:54 qemu.sasl[K
drwxr-xr-x  4 root root   4096 Feb 11 15:54 qga[K
drwxr-xr-x  2 root root   4096 Feb 11 15:54 qobject[K
drwxr-xr-x  2 root root   4096 Feb 11 15:54 qom[K
-rw-r--r--  1 root root  22277 Feb 11 15:54 qtest.c[K
drwxr-xr-x  2 root root   4096 Feb 11 15:54 replay[K
-rw-r--r--  1 root root   2524 Feb 11 15:54 replication.c[K
-rw-r--r--  1 root root   5309 Feb 11 15:54 replication.h[K
drwxr-xr-x 16 root root   4096 Feb 11 15:54 roms[K
-rw-r--r--  1 root root  16533 Feb 11 15:54 rules.mak[K
drwxr-xr-x 11 root root   4096 Feb 11 15:54 scripts[K
drwxr-xr-x  2 root root   4096 Feb 11 15:54 scsi[K
drwxr-xr-x  2 root root   4096 Feb 11 15:54 slirp[K
drwxr-xr-x  2 root root   4096 Feb 11 15:54 stubs[K
drwxr-xr-x 23 root root   4096 Feb 11 15:54 target[K
drwxr-xr-x 11 root root   4096 Feb 11 15:54 tcg[K
drwxr-xr-x 22 root root   4096 Feb 11 15:54 tests[K
-rw-r--r--  1 root root   9307 Feb 11 15:54 thunk.c[K
drwxr-xr-x  3 root root   4096 Feb 11 15:54 tools[K
-rw-r--r--  1 root root   5578 Feb 11 15:54 tpm.c[K
drwxr-xr-x  2 root root   4096 Feb 11 15:54 trace[K
-rw-r--r--  1 root root   7989 Feb 11 15:54 trace-events[K
drwxr-xr-x  5 root root   4096 Feb 11 15:54 ui[K
drwxr-xr-x  2 root root   4096 Feb 11 15:54 util[K
-rw-r--r--  1 root root    790 Feb 11 15:54 version.rc[K
-rw-r--r--  1 root root 135378 Feb 11 15:54 vl.c[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[28;15H[?12l[?25hlxc exec f1 -- ls -al /opt/qemu/[C[1@e[1@d[2;28r[28;1H
[1;28r[28;1H[2;28r[4S[24dtotal 2680
drwxr-xr-x 53 root root   4096 Feb 11 16:18 .
drwxr-xr-x  1 root root      8 Feb 11 16:22 ..
-rw-r--r--  1 root root   1101 Feb 11 15:54 .cirrus.yml
-rw-r--r--  1 root root     75 Feb 11 15:54 .dir-locals.el[1;28r[28;59H[2;28r[5S[24d-rw-r--r--  1 root root    748 Feb 11 15:54 .editorconfig
-rw-r--r--  1 root root    220 Feb 11 15:54 .exrc
-rw-r--r--  1 root root    326 Feb 11 15:54 .gdbinit
drwxr-xr-x  8 root root   4096 Feb 11 15:54 .git[1;28r[28;1H[2;28r[26S[2d-rw-r--r--  1 root root   3136 Feb 11 15:54 .gitignore
-rw-r--r--  1 root root   1657 Feb 11 15:54 .gitlab-ci-edk2.yml
drwxr-xr-x  3 root root   4096 Feb 11 15:54 .gitlab-ci.d
-rw-r--r--  1 root root   3954 Feb 11 15:54 .gitlab-ci.yml
-rw-r--r--  1 root root   1945 Feb 11 15:54 .gitmodules
-rw-r--r--  1 root root   1650 Feb 11 15:54 .gitpublish
-rw-r--r--  1 root root   7362 Feb 11 15:54 .mailmap
-rw-r--r--  1 root root   8601 Feb 11 15:54 .patchew.yml
-rw-r--r--  1 root root    543 Feb 11 15:54 .readthedocs.yml
-rw-r--r--  1 root root   1309 Feb 11 15:54 .shippable.yml
-rw-r--r--  1 root root  17068 Feb 11 15:54 .travis.yml
-rw-r--r--  1 root root  21518 Feb 11 15:54 CODING_STYLE.rst
-rw-r--r--  1 root root  17992 Feb 11 15:54 COPYING
-rw-r--r--  1 root root  26530 Feb 11 15:54 COPYING.LIB
-rw-r--r--  1 root root  23143 Feb 11 15:54 Changelog
-rw-r--r--  1 root root    511 Feb 11 15:54 Kconfig.host
-rw-r--r--  1 root root   1177 Feb 11 15:54 LICENSE
-rw-r--r--  1 root root  61647 Feb 11 15:54 MAINTAINERS
-rw-r--r--  1 root root  45961 Feb 11 15:54 Makefile
-rw-r--r--  1 root root   6302 Feb 11 15:54 Makefile.objs
-rw-r--r--  1 root root   7514 Feb 11 15:54 Makefile.target
-rw-r--r--  1 root root   4936 Feb 11 15:54 README.rst
-rw-r--r--  1 root root      7 Feb 11 15:54 VERSION
drwxr-xr-x  5 root root   4096 Feb 11 15:54 accel
-rw-r--r--  1 root root   3235 Feb 11 15:54 arch_init.c
drwxr-xr-x  2 root root   4096 Feb 11 15:54 audio
drwxr-xr-x  2 root root   4096 Feb 11 15:54 authz[1;28r[28;50H[2;28r[22S[7ddrwxr-xr-x  2 root root   4096 Feb 11 15:54 backends
-rw-r--r--  1 root root   3582 Feb 11 15:54 balloon.c
drwxr-xr-x  2 root root   4096 Feb 11 15:54 block
-rw-r--r--  1 root root 203847 Feb 11 15:54 block.c
-rw-r--r--  1 root root   6763 Feb 11 15:54 blockdev-nbd.c
-rw-r--r--  1 root root 143069 Feb 11 15:54 blockdev.c
-rw-r--r--  1 root root  15589 Feb 11 15:54 blockjob.c
-rw-r--r--  1 root root  11534 Feb 11 15:54 bootdevice.c
drwxr-xr-x  9 root root   4096 Feb 11 15:54 bsd-user
drwxr-xr-x  2 root root   4096 Feb 11 15:54 capstone
drwxr-xr-x  2 root root   4096 Feb 11 15:54 chardev
-rwxr-xr-x  1 root root 215409 Feb 11 15:54 configure
drwxr-xr-x 13 root root   4096 Feb 11 15:54 contrib
-rw-r--r--  1 root root  10313 Feb 11 15:54 cpus-common.c
-rw-r--r--  1 root root  62673 Feb 11 15:54 cpus.c
drwxr-xr-x  2 root root   4096 Feb 11 15:54 crypto
drwxr-xr-x  2 root root   4096 Feb 11 15:54 default-configs
-rw-r--r--  1 root root   2615 Feb 11 15:54 device-hotplug.c
-rw-r--r--  1 root root  14904 Feb 11 15:54 device_tree.c
drwxr-xr-x  3 root root   4096 Feb 11 15:54 disas
-rw-r--r--  1 root root  21166 Feb 11 15:54 disas.c[1;28r[28;1H[2;28r[27S[2d-rw-r--r--  1 root root    113 Feb 11 15:54 module-common.c
drwxr-xr-x  2 root root   4096 Feb 11 15:54 monitor
drwxr-xr-x  2 root root   4096 Feb 11 15:54 nbd
drwxr-xr-x  3 root root   4096 Feb 11 15:54 net
-rw-r--r--  1 root root   8752 Feb 11 15:54 os-posix.c
-rw-r--r--  1 root root   2411 Feb 11 15:54 os-win32.c
drwxr-xr-x  6 root root   4096 Feb 11 15:54 pc-bios
drwxr-xr-x  2 root root   4096 Feb 11 15:54 plugins
drwxr-xr-x  2 root root   4096 Feb 11 15:54 po
drwxr-xr-x  3 root root   4096 Feb 11 15:54 python
drwxr-xr-x  2 root root   4096 Feb 11 15:54 qapi
-rw-r--r--  1 root root  27878 Feb 11 15:54 qdev-monitor.c
-rw-r--r--  1 root root  12018 Feb 11 15:54 qemu-bridge-helper.c
-rw-r--r--  1 root root  15976 Feb 11 15:54 qemu-deprecated.texi
-rw-r--r--  1 root root  93723 Feb 11 15:54 qemu-doc.texi
-rw-r--r--  1 root root   3459 Feb 11 15:54 qemu-edid.c
-rw-r--r--  1 root root   4942 Feb 11 15:54 qemu-img-cmds.hx
-rw-r--r--  1 root root 152401 Feb 11 15:54 qemu-img.c
-rw-r--r--  1 root root  65566 Feb 11 15:54 qemu-io-cmds.c
-rw-r--r--  1 root root  18890 Feb 11 15:54 qemu-io.c
-rw-r--r--  1 root root   7528 Feb 11 15:54 qemu-keymap.c
-rw-r--r--  1 root root  35820 Feb 11 15:54 qemu-nbd.c
-rw-r--r--  1 root root   1118 Feb 11 15:54 qemu-option-trace.texi
-rw-r--r--  1 root root   1042 Feb 11 15:54 qemu-options-wrapper.h
-rw-r--r--  1 root root   1401 Feb 11 15:54 qemu-options.h
-rw-r--r--  1 root root 204778 Feb 11 15:54 qemu-options.hx[1;28r[28;1H[2;28r[4S[24d-rw-r--r--  1 root root  11672 Feb 11 15:54 qemu-seccomp.c
-rw-r--r--  1 root root   5466 Feb 11 15:54 qemu-tech.texi
-rw-r--r--  1 root root   7589 Feb 11 15:54 qemu.nsi
-rw-r--r--  1 root root   1795 Feb 11 15:54 qemu.sasl[1;28r[28;1H[2;28r[25S[3ddrwxr-xr-x  4 root root   4096 Feb 11 15:54 qga
drwxr-xr-x  2 root root   4096 Feb 11 15:54 qobject
drwxr-xr-x  2 root root   4096 Feb 11 15:54 qom
-rw-r--r--  1 root root  22277 Feb 11 15:54 qtest.c
drwxr-xr-x  2 root root   4096 Feb 11 15:54 replay
-rw-r--r--  1 root root   2524 Feb 11 15:54 replication.c
-rw-r--r--  1 root root   5309 Feb 11 15:54 replication.h
drwxr-xr-x 16 root root   4096 Feb 11 15:54 roms
-rw-r--r--  1 root root  16533 Feb 11 15:54 rules.mak
drwxr-xr-x 11 root root   4096 Feb 11 15:54 scripts
drwxr-xr-x  2 root root   4096 Feb 11 15:54 scsi
drwxr-xr-x  2 root root   4096 Feb 11 15:54 slirp
drwxr-xr-x  2 root root   4096 Feb 11 15:54 stubs
drwxr-xr-x 23 root root   4096 Feb 11 15:54 target
drwxr-xr-x 11 root root   4096 Feb 11 15:54 tcg
drwxr-xr-x 22 root root   4096 Feb 11 15:54 tests
-rw-r--r--  1 root root   9307 Feb 11 15:54 thunk.c
drwxr-xr-x  3 root root   4096 Feb 11 15:54 tools
-rw-r--r--  1 root root   5578 Feb 11 15:54 tpm.c
drwxr-xr-x  2 root root   4096 Feb 11 15:54 trace
-rw-r--r--  1 root root   7989 Feb 11 15:54 trace-events
drwxr-xr-x  5 root root   4096 Feb 11 15:54 ui
drwxr-xr-x  2 root root   4096 Feb 11 15:54 util
-rw-r--r--  1 root root    790 Feb 11 15:54 version.rc
-rw-r--r--  1 root root 135378 Feb 11 15:54 vl.c[1;28r[28;1H[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[2;1H-rw-r--r--  1 root root   1795 Feb 11 15:54 qemu.sasl[K
drwxr-xr-x  4 root root   4096 Feb 11 15:54 qga[K
drwxr-xr-x  2 root root   4096 Feb 11 15:54 qobject[K
drwxr-xr-x  2 root root   4096 Feb 11 15:54 qom[K
-rw-r--r--  1 root root  22277 Feb 11 15:54 qtest.c[K
drwxr-xr-x  2 root root   4096 Feb 11 15:54 replay[K
-rw-r--r--  1 root root   2524 Feb 11 15:54 replication.c[K
-rw-r--r--  1 root root   5309 Feb 11 15:54 replication.h[K
drwxr-xr-x 16 root root   4096 Feb 11 15:54 roms[K
-rw-r--r--  1 root root  16533 Feb 11 15:54 rules.mak[K
drwxr-xr-x 11 root root   4096 Feb 11 15:54 scripts[K
drwxr-xr-x  2 root root   4096 Feb 11 15:54 scsi[K
drwxr-xr-x  2 root root   4096 Feb 11 15:54 slirp[K
drwxr-xr-x  2 root root   4096 Feb 11 15:54 stubs[K
drwxr-xr-x 23 root root   4096 Feb 11 15:54 target[K
drwxr-xr-x 11 root root   4096 Feb 11 15:54 tcg[K
drwxr-xr-x 22 root root   4096 Feb 11 15:54 tests[K
-rw-r--r--  1 root root   9307 Feb 11 15:54 thunk.c[K
drwxr-xr-x  3 root root   4096 Feb 11 15:54 tools[K
-rw-r--r--  1 root root   5578 Feb 11 15:54 tpm.c[K
drwxr-xr-x  2 root root   4096 Feb 11 15:54 trace[K
-rw-r--r--  1 root root   7989 Feb 11 15:54 trace-events[K
drwxr-xr-x  5 root root   4096 Feb 11 15:54 ui[K
drwxr-xr-x  2 root root   4096 Feb 11 15:54 util[K
-rw-r--r--  1 root root    790 Feb 11 15:54 version.rc[K
-rw-r--r--  1 root root 135378 Feb 11 15:54 vl.c[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[28;15H[?12l[?25hclear[2;28r[28;1H
[1;28r[28;1H[2;28r[2;1H[J[1;28r[2;1H[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[2;15H[?12l[?25h# It's also writable for each container which is very impr[Kortant.
[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[32m[1m[2;1Hroot@e1-vm(B[m:[34m[1m~(B[m# # It's also writable for each container which is very important.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[3;15H[?12l[?25hlxc exec f1 -- touch /opt/qemu/f1-file
[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[32m[1m[2;1Hroot@e1-vm(B[m:[34m[1m~(B[m# # It's also writable for each container which is very important.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec f1 -- touch /opt/qemu/f1-file[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[4;15H[?12l[?25hlxc exec f1 -- touch /opt/qemu/f1-file[1@e[1@d
[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[32m[1m[2;1Hroot@e1-vm(B[m:[34m[1m~(B[m# # It's also writable for each container which is very important.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec f1 -- touch /opt/qemu/f1-file[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec fed1 -- touch /opt/qemu/f1-file[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[5;15H[?12l[?25hlxc exec fed1 -- touch /opt/qemu/f1-file[C[1P[1P[1@o[C[1@1[1P[1P[1P[1@o
[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[32m[1m[2;1Hroot@e1-vm(B[m:[34m[1m~(B[m# # It's also writable for each container which is very important.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec f1 -- touch /opt/qemu/f1-file[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec fed1 -- touch /opt/qemu/f1-file[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec o1 -- touch /opt/qemu/f1-file[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[6;15H[?12l[?25hlxc exec o1 -- touch /opt/qemu/f1-file[C[C[C[C[C[C[C[C[C[C[1P1-file[6Do1-file[6D
[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[32m[1m[2;1Hroot@e1-vm(B[m:[34m[1m~(B[m# # It's also writable for each container which is very important.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec f1 -- touch /opt/qemu/f1-file[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec fed1 -- touch /opt/qemu/f1-file[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec o1 -- touch /opt/qemu/f1-file[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec o1 -- touch /opt/qemu/o1-file[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[7;15H[?12l[?25hlxc exec o1 -- touch /opt/qemu/o1-file[1P[1@e[1P[1@f[1@e[1@d[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[1P1-file[6Df1-file[6De1-file[6Dd1-file[6D
[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[32m[1m[2;1Hroot@e1-vm(B[m:[34m[1m~(B[m# # It's also writable for each container which is very important.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec f1 -- touch /opt/qemu/f1-file[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec fed1 -- touch /opt/qemu/f1-file[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec o1 -- touch /opt/qemu/f1-file[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec o1 -- touch /opt/qemu/o1-file[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec fed1 -- touch /opt/qemu/fed1-file[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[8;15H[?12l[?25hclear
[2;28r[2;1H[J[1;28r[2;1H[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[2;15H[?12l[?25hlxc st[K[Kexec f1 -- stat /opt/qemu-[K/f1-fie[Kle
  File: /opt/qemu/f1-file
  Size: 0         [6CBlocks: 0          IO Block: 4096   regular empty file
Device: 801h/2049d[6CInode: 92463       Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2020-02-11 16:23:50.762297361 +0000
Modify: 2020-02-11 16:23:50.762297361 +0000
Change: 2020-02-11 16:23:50.762297361 +0000
 Birth: -
[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[32m[1m[2;1Hroot@e1-vm(B[m:[34m[1m~(B[m# lxc exec f1 -- stat /opt/qemu/f1-file[K
  File: /opt/qemu/f1-file[K
  Size: 0         [6X[6CBlocks: 0          IO Block: 4096   regular empty file[K
Device: 801h/2049d[6X[6CInode: 92463       Links: 1[K
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)[K
Access: 2020-02-11 16:23:50.762297361 +0000[K
Modify: 2020-02-11 16:23:50.762297361 +0000[K
Change: 2020-02-11 16:23:50.762297361 +0000[K
 Birth: -[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[11;15H[?12l[?25hlxc exec f1 -- stat /opt/qemu/f1-file[1@e[1@d
  File: /opt/qemu/f1-file
  Size: 0         [6CBlocks: 0          IO Block: 4096   regular empty file
Device: 801h/2049d[6CInode: 92463       Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2020-02-11 16:23:50.762297361 +0000
Modify: 2020-02-11 16:23:50.762297361 +0000
Change: 2020-02-11 16:23:50.762297361 +0000
 Birth: 2020-02-11 16:23:41.866465463 +0000
[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[32m[1m[2;1Hroot@e1-vm(B[m:[34m[1m~(B[m# lxc exec f1 -- stat /opt/qemu/f1-file[K
  File: /opt/qemu/f1-file[K
  Size: 0         [6X[6CBlocks: 0          IO Block: 4096   regular empty file[K
Device: 801h/2049d[6X[6CInode: 92463       Links: 1[K
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)[K
Access: 2020-02-11 16:23:50.762297361 +0000[K
Modify: 2020-02-11 16:23:50.762297361 +0000[K
Change: 2020-02-11 16:23:50.762297361 +0000[K
 Birth: -[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec fed1 -- stat /opt/qemu/f1-file[K
  File: /opt/qemu/f1-file[K
  Size: 0         [6X[6CBlocks: 0          IO Block: 4096   regular empty file[K
Device: 801h/2049d[6X[6CInode: 92463       Links: 1[K
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)[K
Access: 2020-02-11 16:23:50.762297361 +0000[K
Modify: 2020-02-11 16:23:50.762297361 +0000[K
Change: 2020-02-11 16:23:50.762297361 +0000[K
 Birth: 2020-02-11 16:23:41.866465463 +0000[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[20;15H[?12l[?25hlxc exec fed1 -- stat /opt/qemu/f1-filee1-file[6Dd1-file[6D
  File: /opt/qemu/fed1-file
  Size: 0         [6CBlocks: 0          IO Block: 4096   regular empty file
Device: 801h/2049d[6CInode: 92465       Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2020-02-11 16:24:05.386024764 +0000
Modify: 2020-02-11 16:24:05.386024764 +0000
Change: 2020-02-11 16:24:05.386024764 +0000[2;28r[28;1H
[A Birth: 2020-02-11 16:24:05.386024764 +0000[1;28r[28;1H[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[2;1H  File: /opt/qemu/f1-file[K
  Size: 0         [6X[6CBlocks: 0          IO Block: 4096   regular empty file[K
Device: 801h/2049d[6X[6CInode: 92463       Links: 1[K
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)[K
Access: 2020-02-11 16:23:50.762297361 +0000[K
Modify: 2020-02-11 16:23:50.762297361 +0000[K
Change: 2020-02-11 16:23:50.762297361 +0000[K
 Birth: -[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec fed1 -- stat /opt/qemu/f1-file[K
  File: /opt/qemu/f1-file[K
  Size: 0         [6X[6CBlocks: 0          IO Block: 4096   regular empty file[K
Device: 801h/2049d[6X[6CInode: 92463       Links: 1[K
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)[K
Access: 2020-02-11 16:23:50.762297361 +0000[K
Modify: 2020-02-11 16:23:50.762297361 +0000[K
Change: 2020-02-11 16:23:50.762297361 +0000[K
 Birth: 2020-02-11 16:23:41.866465463 +0000[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec fed1 -- stat /opt/qemu/fed1-file[K
  File: /opt/qemu/fed1-file[K
  Size: 0         [6X[6CBlocks: 0          IO Block: 4096   regular empty file[K
Device: 801h/2049d[6X[6CInode: 92465       Links: 1[K
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)[K
Access: 2020-02-11 16:24:05.386024764 +0000[K
Modify: 2020-02-11 16:24:05.386024764 +0000[K
Change: 2020-02-11 16:24:05.386024764 +0000[K
 Birth: 2020-02-11 16:24:05.386024764 +0000[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[28;15H[?12l[?25hlxc exec fed1 -- stat /opt/qemu/fed1-file[C[1P[1P[1P[1@o[2;28r[28;1H
[1;28r[28;1H[2;28r[3S[25d  File: /opt/qemu/fed1-file
  Size: 0         [6CBlocks: 0          IO Block: 4096   regular empty file
Device: 801h/2049d[6CInode: 92465       Links: 1[1;28r[28;1H[2;28r[5S[23dAccess: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2020-02-11 16:24:05.386024764 +0000
Modify: 2020-02-11 16:24:05.386024764 +0000
Change: 2020-02-11 16:24:05.386024764 +0000
 Birth: 2020-02-11 16:24:05.386024764 +0000[1;28r[28;1H[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[2;1H  File: /opt/qemu/f1-file[K
  Size: 0         [6X[6CBlocks: 0          IO Block: 4096   regular empty file[K
Device: 801h/2049d[6X[6CInode: 92463       Links: 1[K
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)[K
Access: 2020-02-11 16:23:50.762297361 +0000[K
Modify: 2020-02-11 16:23:50.762297361 +0000[K
Change: 2020-02-11 16:23:50.762297361 +0000[K
 Birth: 2020-02-11 16:23:41.866465463 +0000[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec fed1 -- stat /opt/qemu/fed1-file[K
  File: /opt/qemu/fed1-file[K
  Size: 0         [6X[6CBlocks: 0          IO Block: 4096   regular empty file[K
Device: 801h/2049d[6X[6CInode: 92465       Links: 1[K
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)[K
Access: 2020-02-11 16:24:05.386024764 +0000[K
Modify: 2020-02-11 16:24:05.386024764 +0000[K
Change: 2020-02-11 16:24:05.386024764 +0000[K
 Birth: 2020-02-11 16:24:05.386024764 +0000[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec o1 -- stat /opt/qemu/fed1-file[K
  File: /opt/qemu/fed1-file[K
  Size: 0         [6X[6CBlocks: 0          IO Block: 4096   regular empty file[K
Device: 801h/2049d[6X[6CInode: 92465       Links: 1[K
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)[K
Access: 2020-02-11 16:24:05.386024764 +0000[K
Modify: 2020-02-11 16:24:05.386024764 +0000[K
Change: 2020-02-11 16:24:05.386024764 +0000[K
 Birth: 2020-02-11 16:24:05.386024764 +0000[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[28;15H[?12l[?25hlxc exec o1 -- stat /opt/qemu/fed1-file[1P1-file[6D[1P1-file[6D[1P1-file[6Do1-file[6D[2;28r[28;1H
[1;28r[28;1H[2;28r[8S[20d  File: /opt/qemu/o1-file
  Size: 0         [6CBlocks: 0          IO Block: 4096   regular empty file
Device: 801h/2049d[6CInode: 92464       Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2020-02-11 16:23:57.718167126 +0000
Modify: 2020-02-11 16:23:57.718167126 +0000
Change: 2020-02-11 16:23:57.718167126 +0000
 Birth: 2020-02-11 16:23:57.718167126 +0000[1;28r[28;1H[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[2;1H  File: /opt/qemu/fed1-file[K
  Size: 0         [6X[6CBlocks: 0          IO Block: 4096   regular empty file[K
Device: 801h/2049d[6X[6CInode: 92465       Links: 1[K
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)[K
Access: 2020-02-11 16:24:05.386024764 +0000[K
Modify: 2020-02-11 16:24:05.386024764 +0000[K
Change: 2020-02-11 16:24:05.386024764 +0000[K
 Birth: 2020-02-11 16:24:05.386024764 +0000[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec o1 -- stat /opt/qemu/fed1-file[K
  File: /opt/qemu/fed1-file[K
  Size: 0         [6X[6CBlocks: 0          IO Block: 4096   regular empty file[K
Device: 801h/2049d[6X[6CInode: 92465       Links: 1[K
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)[K
Access: 2020-02-11 16:24:05.386024764 +0000[K
Modify: 2020-02-11 16:24:05.386024764 +0000[K
Change: 2020-02-11 16:24:05.386024764 +0000[K
 Birth: 2020-02-11 16:24:05.386024764 +0000[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# lxc exec o1 -- stat /opt/qemu/o1-file[K
  File: /opt/qemu/o1-file[K
  Size: 0         [6X[6CBlocks: 0          IO Block: 4096   regular empty file[K
Device: 801h/2049d[6X[6CInode: 92464       Links: 1[K
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)[K
Access: 2020-02-11 16:23:57.718167126 +0000[K
Modify: 2020-02-11 16:23:57.718167126 +0000[K
Change: 2020-02-11 16:23:57.718167126 +0000[K
 Birth: 2020-02-11 16:23:57.718167126 +0000[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[28;15H[?12l[?25hclear[2;28r[28;1H
[1;28r[28;1H[2;28r[2;1H[J[1;28r[2;1H[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[2;15H[?12l[?25h# And the fsid mappings will take care that all those files a[Khave the expected p[Kownerhip[K[K[Kship
[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[32m[1m[2;1Hroot@e1-vm(B[m:[34m[1m~(B[m# # And the fsid mappings will take care that all those files have the expected ownership[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[3;15H[?12l[?25h# on the host.
[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[32m[1m[2;1Hroot@e1-vm(B[m:[34m[1m~(B[m# # And the fsid mappings will take care that all those files have the expected ownership[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # on the host.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[4;15H[?12l[?25hls -al /srv/qemu/{f1,fed1,o1}-file
-rw-r--r-- 1 300000 300000 0 Feb 11 16:23 /srv/qemu/f1-file
-rw-r--r-- 1 300000 300000 0 Feb 11 16:24 /srv/qemu/fed1-file
-rw-r--r-- 1 300000 300000 0 Feb 11 16:23 /srv/qemu/o1-file
[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[32m[1m[2;1Hroot@e1-vm(B[m:[34m[1m~(B[m# # And the fsid mappings will take care that all those files have the expected ownership[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # on the host.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# ls -al /srv/qemu/{f1,fed1,o1}-file[K
-rw-r--r-- 1 300000 300000 0 Feb 11 16:23 /srv/qemu/f1-file[K
-rw-r--r-- 1 300000 300000 0 Feb 11 16:24 /srv/qemu/fed1-file[K
-rw-r--r-- 1 300000 300000 0 Feb 11 16:23 /srv/qemu/o1-file[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[8;15H[?12l[?25hls -al /srv/qemu/{f1,fed1,o1}-file[1P /srv/qemu/{f1,fed1,o1}-file[20G[1P /srv/qemu/{f1,fed1,o1}-file[19G[1P /srv/qemu/{f1,fed1,o1}-file[18G[1P/srv/qemu/{f1,fed1,o1}-file[17G[1P /srv/qemu/{f1,fed1,o1}-file[16G[1P /srv/qemu/{f1,fed1,o1}-file[15Gs /srv/qemu/{f1,fed1,o1}-file[16Gt /srv/qemu/{f1,fed1,o1}-file[17Ga /srv/qemu/{f1,fed1,o1}-file[18Gt /srv/qemu/{f1,fed1,o1}-file[19G
  File: /srv/qemu/f1-file
  Size: 0         [6CBlocks: 0          IO Block: 4096   regular empty file
Device: 801h/2049d[6CInode: 92463       Links: 1
Access: (0644/-rw-r--r--)  Uid: (300000/ UNKNOWN)   Gid: (300000/ UNKNOWN)
Access: 2020-02-11 16:23:50.762297361 +0000
Modify: 2020-02-11 16:23:50.762297361 +0000
Change: 2020-02-11 16:23:50.762297361 +0000
 Birth: -
  File: /srv/qemu/fed1-file
  Size: 0         [6CBlocks: 0          IO Block: 4096   regular empty file
Device: 801h/2049d[6CInode: 92465       Links: 1
Access: (0644/-rw-r--r--)  Uid: (300000/ UNKNOWN)   Gid: (300000/ UNKNOWN)
Access: 2020-02-11 16:24:05.386024764 +0000
Modify: 2020-02-11 16:24:05.386024764 +0000
[2;28r[5S[18dChange: 2020-02-11 16:24:05.386024764 +0000
 Birth: -
  File: /srv/qemu/o1-file
  Size: 0         [6CBlocks: 0          IO Block: 4096   regular empty file
Device: 801h/2049d[6CInode: 92464       Links: 1
Access: (0644/-rw-r--r--)  Uid: (300000/ UNKNOWN)   Gid: (300000/ UNKNOWN)
Access: 2020-02-11 16:23:57.718167126 +0000
Modify: 2020-02-11 16:23:57.718167126 +0000
Change: 2020-02-11 16:23:57.718167126 +0000
 Birth: -[1;28r[28;1H[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[2;1H-rw-r--r-- 1 300000 300000 0 Feb 11 16:23 /srv/qemu/o1-file[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# stat /srv/qemu/{f1,fed1,o1}-file[K
  File: /srv/qemu/f1-file[K
  Size: 0         [6X[6CBlocks: 0          IO Block: 4096   regular empty file[K
Device: 801h/2049d[6X[6CInode: 92463       Links: 1[K
Access: (0644/-rw-r--r--)  Uid: (300000/ UNKNOWN)   Gid: (300000/ UNKNOWN)[K
Access: 2020-02-11 16:23:50.762297361 +0000[K
Modify: 2020-02-11 16:23:50.762297361 +0000[K
Change: 2020-02-11 16:23:50.762297361 +0000[K
 Birth: -[K
  File: /srv/qemu/fed1-file[K
  Size: 0         [6X[6CBlocks: 0          IO Block: 4096   regular empty file[K
Device: 801h/2049d[6X[6CInode: 92465       Links: 1[K
Access: (0644/-rw-r--r--)  Uid: (300000/ UNKNOWN)   Gid: (300000/ UNKNOWN)[K
Access: 2020-02-11 16:24:05.386024764 +0000[K
Modify: 2020-02-11 16:24:05.386024764 +0000[K
Change: 2020-02-11 16:24:05.386024764 +0000[K
 Birth: -[K
  File: /srv/qemu/o1-file[K
  Size: 0         [6X[6CBlocks: 0          IO Block: 4096   regular empty file[K
Device: 801h/2049d[6X[6CInode: 92464       Links: 1[K
Access: (0644/-rw-r--r--)  Uid: (300000/ UNKNOWN)   Gid: (300000/ UNKNOWN)[K
Access: 2020-02-11 16:23:57.718167126 +0000[K
Modify: 2020-02-11 16:23:57.718167126 +0000[K
Change: 2020-02-11 16:23:57.718167126 +0000[K
 Birth: -[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[28;15H[?12l[?25hT[K# That's it. This way we can share storage between containers with differn[Kent id mappings.[2;28r[28;1H
[1;28r[28;1H[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[32m[1m[2;1Hroot@e1-vm(B[m:[34m[1m~(B[m# stat /srv/qemu/{f1,fed1,o1}-file[K
  File: /srv/qemu/f1-file[K
  Size: 0         [6X[6CBlocks: 0          IO Block: 4096   regular empty file[K
Device: 801h/2049d[6X[6CInode: 92463       Links: 1[K
Access: (0644/-rw-r--r--)  Uid: (300000/ UNKNOWN)   Gid: (300000/ UNKNOWN)[K
Access: 2020-02-11 16:23:50.762297361 +0000[K
Modify: 2020-02-11 16:23:50.762297361 +0000[K
Change: 2020-02-11 16:23:50.762297361 +0000[K
 Birth: -[K
  File: /srv/qemu/fed1-file[K
  Size: 0         [6X[6CBlocks: 0          IO Block: 4096   regular empty file[K
Device: 801h/2049d[6X[6CInode: 92465       Links: 1[K
Access: (0644/-rw-r--r--)  Uid: (300000/ UNKNOWN)   Gid: (300000/ UNKNOWN)[K
Access: 2020-02-11 16:24:05.386024764 +0000[K
Modify: 2020-02-11 16:24:05.386024764 +0000[K
Change: 2020-02-11 16:24:05.386024764 +0000[K
 Birth: -[K
  File: /srv/qemu/o1-file[K
  Size: 0         [6X[6CBlocks: 0          IO Block: 4096   regular empty file[K
Device: 801h/2049d[6X[6CInode: 92464       Links: 1[K
Access: (0644/-rw-r--r--)  Uid: (300000/ UNKNOWN)   Gid: (300000/ UNKNOWN)[K
Access: 2020-02-11 16:23:57.718167126 +0000[K
Modify: 2020-02-11 16:23:57.718167126 +0000[K
Change: 2020-02-11 16:23:57.718167126 +0000[K
 Birth: -[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# # That's it. This way we can share storage between containers with different id mappings.[K[32m[1m
root@e1-vm(B[m:[34m[1m~(B[m# [K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[28;15H[?12l[?25hclear[2;28r[28;1H
[1;28r[28;1H[2;28r[2;1H[J[1;28r[2;1H[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [?25l[32m[1mroot@e1-vm(B[m:[34m[1m~(B[m# [K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;230m[48;5;239m[H[$5|demo]                                        0:0- 1:1*                                        [%18|0|root@e1-vm: ~] (B[m[2;15H[?12l[?25h[1;28r(B[m[?1l>[H[2J]112[?12l[?25h[?1000l[?1002l[?1006l[?1005l[detached (from session demo)]
[0;32m[0m[1;34mbrauner[1;37m@[1;33mwittgenstein[1;37m|[1;33m~/src/git/cground/shiftfs_fsid_perf[1;32m[1;37m|[1;36mgithub-master %<>
[0m[1;34m>[0m[0;32m[0m exit

Script done on 2020-02-12 12:48:31+01:00 [COMMAND_EXIT_CODE="0"]
